import { PageHeading, Tag } from "@/components/AcademyUI";
import { useLocale } from "@/contexts/LocaleContext";
import { text } from "@/lib/i18n";
import { googleEcosystemStatement, googleLearningTracks } from "@shared/googleEcosystemContent";
import { ArrowUpRight, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

const copy = { es: { eyebrow: "Ruta complementaria", title: "Aprende el ecosistema Google con criterio.", description: "Material original de UX Academy que organiza fuentes públicas y abiertas por decisiones profesionales, prácticas y límites de uso.", tracks: "rutas", units: "unidades", sources: "fuentes verificadas", all: "Todas", outcome: "Al finalizar", studio: "Studio brief", deliverable: "Entregable", guardrail: "Límite de práctica", resources: "Fuentes y condiciones", open: "Abierto / reutilizable", linked: "Acceso público · enlazado", attribution: "Uso y atribución" }, pt: { eyebrow: "Trilha complementar", title: "Aprenda o ecossistema Google com critério.", description: "Material original da UX Academy que organiza fontes públicas e abertas por decisões profissionais, práticas e limites de uso.", tracks: "trilhas", units: "unidades", sources: "fontes verificadas", all: "Todas", outcome: "Ao finalizar", studio: "Studio brief", deliverable: "Entregável", guardrail: "Limite de prática", resources: "Fontes e condições", open: "Aberto / reutilizável", linked: "Acesso público · link", attribution: "Uso e atribuição" }, en: { eyebrow: "Companion pathway", title: "Learn the Google ecosystem with judgment.", description: "Original UX Academy material that organizes public and open sources around professional decisions, practice, and use boundaries.", tracks: "tracks", units: "units", sources: "verified sources", all: "All", outcome: "By the end", studio: "Studio brief", deliverable: "Deliverable", guardrail: "Practice boundary", resources: "Sources and conditions", open: "Open / reusable", linked: "Public access · linked", attribution: "Use and attribution" } } as const;

export default function GoogleEcosystem() {
  const { locale } = useLocale();
  const ui = copy[locale];
  const [domain, setDomain] = useState("all");
  const [activeId, setActiveId] = useState(googleLearningTracks[0].id);
  const domains = useMemo(() => Array.from(new Set(googleLearningTracks.map(track => text(track.domain, locale)))), [locale]);
  const visibleTracks = googleLearningTracks.filter(track => domain === "all" || text(track.domain, locale) === domain);
  const active = googleLearningTracks.find(track => track.id === activeId) ?? visibleTracks[0] ?? googleLearningTracks[0];
  const sourceCount = googleLearningTracks.reduce((total, track) => total + track.resources.length, 0);
  return <>
    <PageHeading eyebrow={ui.eyebrow} title={ui.title} description={ui.description} />
    <section className="mb-8 grid gap-3 sm:grid-cols-3"><div className="rounded-[1.5rem] bg-[#1d45a5] p-5 text-white shadow-[5px_5px_0_#ffd264]"><p className="font-serif text-3xl">{googleLearningTracks.length}</p><p className="mt-1 text-sm text-[#cfdbff]">{ui.tracks}</p></div><div className="rounded-[1.5rem] border border-[#d9e2f2] bg-[#e7f7e4] p-5"><p className="font-serif text-3xl text-[#184d31]">{googleLearningTracks.length * 3}</p><p className="mt-1 text-sm text-[#4f705b]">{ui.units}</p></div><div className="rounded-[1.5rem] border border-[#d9e2f2] bg-[#fff0cf] p-5"><p className="font-serif text-3xl text-[#793d0d]">{sourceCount}</p><p className="mt-1 text-sm text-[#7a5a37]">{ui.sources}</p></div></section>
    <section className="mb-7 rounded-[1.5rem] border border-[#d8e2f8] bg-[#edf3ff] p-4 text-sm leading-6 text-[#526381]"><div className="flex items-center gap-2 font-bold text-[#1d45a5]"><ShieldCheck size={17}/>{ui.attribution}</div><p className="mt-2">{text(googleEcosystemStatement, locale)}</p></section>
    <div className="mb-6 flex flex-wrap gap-2"><button onClick={() => setDomain("all")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${domain === "all" ? "bg-[#1d45a5] text-white" : "bg-[#eaf0fb] text-[#566785]"}`}>{ui.all}</button>{domains.map(item => <button key={item} onClick={() => setDomain(item)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${domain === item ? "bg-[#1d45a5] text-white" : "bg-[#eaf0fb] text-[#566785]"}`}>{item}</button>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(270px,.8fr)_minmax(0,1.8fr)]"><aside className="grid content-start gap-3 sm:grid-cols-2 xl:grid-cols-1">{visibleTracks.map(track => <button key={track.id} onClick={() => setActiveId(track.id)} className={`rounded-[1.35rem] border p-4 text-left transition ${active.id === track.id ? "border-[#1d45a5] bg-[#1d45a5] text-white shadow-[5px_5px_0_#ffd264]" : "border-[#dce4f1] bg-white hover:border-[#7494dc]"}`}><p className={`text-[10px] font-bold uppercase tracking-[.16em] ${active.id === track.id ? "text-[#ffd977]" : "text-[#3155a7]"}`}>{String(track.order).padStart(2, "0")} · {text(track.level, locale)}</p><h2 className="mt-2 font-serif text-xl leading-tight">{text(track.title, locale)}</h2><p className={`mt-2 text-xs leading-5 ${active.id === track.id ? "text-[#cfdbff]" : "text-[#657493]"}`}>{text(track.domain, locale)}</p></button>)}</aside>
      <article className="rounded-[1.8rem] border border-[#dce4f1] bg-white p-5 shadow-[0_18px_40px_-35px_rgba(23,50,125,.85)] md:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><Tag tone="forest">{text(active.domain, locale)}</Tag><h1 className="mt-4 font-serif text-4xl leading-[1.02] text-[#1b2445] md:text-5xl">{text(active.title, locale)}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[#566481] md:text-base">{text(active.overview, locale)}</p></div><span className="rounded-full bg-[#fff0cf] px-3 py-1.5 text-xs font-bold text-[#854613]">{text(active.level, locale)}</span></div>
        <section className="mt-8"><h2 className="font-serif text-2xl text-[#1b2445]">{ui.outcome}</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{active.outcomes.map(item => <div key={text(item, locale)} className="flex gap-2 rounded-xl bg-[#edf3ff] p-3 text-sm leading-5 text-[#4d5f82]"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#1d45a5]"/>{text(item, locale)}</div>)}</div></section>
        <section className="mt-8"><h2 className="font-serif text-2xl text-[#1b2445]">{locale === "es" ? "Unidades aplicadas" : locale === "pt" ? "Unidades aplicadas" : "Applied units"}</h2><div className="mt-3 grid gap-3">{active.units.map((item, index) => <div key={text(item.title, locale)} className="rounded-[1.25rem] border border-[#e0e7f2] p-4"><div className="flex gap-4"><span className="font-serif text-2xl text-[#d77135]">0{index + 1}</span><div><h3 className="font-semibold text-[#27345a]">{text(item.title, locale)}</h3><p className="mt-1 text-sm leading-6 text-[#62708d]">{text(item.objective, locale)}</p><p className="mt-3 border-l-2 border-[#ffd264] pl-3 text-sm leading-6 text-[#4a5b7b]">{text(item.practice, locale)}</p></div></div></div>)}</div></section>
        <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-[1.4rem] bg-[#1d45a5] p-5 text-white"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#ffd264]">{ui.studio}</p><p className="mt-3 font-serif text-xl leading-7">{text(active.studioBrief, locale)}</p><div className="mt-5 border-t border-white/15 pt-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#bdccf4]">{ui.deliverable}</p><p className="mt-2 text-sm leading-6 text-[#e0e8ff]">{text(active.deliverable, locale)}</p></div></div><div className="rounded-[1.4rem] bg-[#fff0cf] p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#9c5216]">{ui.guardrail}</p><p className="mt-3 text-sm leading-7 text-[#6e573e]">{text(active.guardrail, locale)}</p></div></section>
        <section className="mt-8"><h2 className="font-serif text-2xl text-[#1b2445]">{ui.resources}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{active.resources.map(resource => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className="group rounded-[1.25rem] border border-[#dce4f1] p-4 transition hover:-translate-y-0.5 hover:border-[#7192dc]"><div className="flex items-center justify-between gap-2"><Tag tone={resource.access === "open" ? "forest" : "neutral"}>{resource.access === "open" ? ui.open : ui.linked}</Tag><ExternalLink size={16} className="text-[#71809d]"/></div><h3 className="mt-4 font-semibold text-[#27345a]">{resource.title}</h3><p className="mt-2 text-sm leading-6 text-[#657493]">{text(resource.note, locale)}</p><p className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#a95d25]">{resource.license}<ArrowUpRight size={13}/></p></a>)}</div></section>
      </article>
    </div>
  </>;
}
