import { PageHeading, Tag } from "@/components/AcademyUI";
import { useLocale } from "@/contexts/LocaleContext";
import { text } from "@/lib/i18n";
import { googleEcosystemStatement, googleLearningTracks } from "@shared/googleEcosystemContent";
import { ArrowUpRight, CheckCircle2, ExternalLink, ShieldCheck } from "lucide-react";
import { useMemo, useState } from "react";

const copy = { es: { eyebrow: "Ruta complementaria", title: "Aprende el ecosistema Google con criterio.", description: "Material original de UX Academy que organiza fuentes públicas y abiertas por decisiones profesionales, prácticas y límites de uso.", tracks: "rutas", units: "unidades", sources: "fuentes verificadas", all: "Todas", outcome: "Al finalizar", studio: "Studio brief", deliverable: "Entregable", guardrail: "Límite de práctica", resources: "Fuentes y condiciones", open: "Abierto / reutilizable", linked: "Acceso público · enlazado", attribution: "Uso y atribución" }, pt: { eyebrow: "Trilha complementar", title: "Aprenda o ecossistema Google com critério.", description: "Material original da UX Academy que organiza fontes públicas e abertas por decisões profissionais, práticas e limites de uso.", tracks: "trilhas", units: "unidades", sources: "fontes verificadas", all: "Todas", outcome: "Ao finalizar", studio: "Studio brief", deliverable: "Entregável", guardrail: "Limite de prática", resources: "Fontes e condições", open: "Aberto / reutilizável", linked: "Acesso público · link", attribution: "Uso e atribuição" }, en: { eyebrow: "Companion pathway", title: "Learn the Google ecosystem with judgment.", description: "Original UX Academy material that organizes public and open sources around professional decisions, practice, and use boundaries.", tracks: "tracks", units: "units", sources: "verified sources", all: "All", outcome: "By the end", studio: "Studio brief", deliverable: "Deliverable", guardrail: "Practice boundary", resources: "Sources and conditions", open: "Open / reusable", linked: "Public access · linked", attribution: "Use and attribution" } } as const;

export default function GoogleEcosystem() {
  const { locale } = useLocale();
  const ui = copy[locale];
  const [domain, setDomain] = useState("all");
  const [activeId, setActiveId] = useState(googleLearningTracks[0].id);
  const domains = useMemo(() => Array.from(new Set(googleLearningTracks.map(track => text(track.domain, locale)))), [locale]);
  const visibleTracks = googleLearningTracks.filter(track => domain === "all" || text(track.domain, locale) === domain);
  const active = googleLearningTracks.find(track => track.id === activeId) ?? visibleTracks[0] ?? googleLearningTracks[0];
  const sourceCount = googleLearningTracks.reduce((total, track) => total + track.resources.length, 0);
  return <>
    <PageHeading eyebrow={ui.eyebrow} title={ui.title} description={ui.description} />
    <section className="mb-8 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-[#1d382d] p-5 text-white"><p className="font-serif text-3xl">{googleLearningTracks.length}</p><p className="mt-1 text-sm text-[#cbd7cc]">{ui.tracks}</p></div><div className="rounded-2xl border border-[#dfd8ce] bg-[#fffdf9] p-5"><p className="font-serif text-3xl">{googleLearningTracks.length * 3}</p><p className="mt-1 text-sm text-[#657064]">{ui.units}</p></div><div className="rounded-2xl border border-[#dfd8ce] bg-[#fffdf9] p-5"><p className="font-serif text-3xl">{sourceCount}</p><p className="mt-1 text-sm text-[#657064]">{ui.sources}</p></div></section>
    <section className="mb-7 rounded-2xl border border-[#d8d0c5] bg-[#f1ece2] p-4 text-sm leading-6 text-[#59665b]"><div className="flex items-center gap-2 font-bold text-[#2d493b]"><ShieldCheck size={17}/>{ui.attribution}</div><p className="mt-2">{text(googleEcosystemStatement, locale)}</p></section>
    <div className="mb-6 flex flex-wrap gap-2"><button onClick={() => setDomain("all")} className={`rounded-full px-3 py-1.5 text-xs font-bold ${domain === "all" ? "bg-[#1d382d] text-white" : "bg-[#e9e3d9] text-[#5c665c]"}`}>{ui.all}</button>{domains.map(item => <button key={item} onClick={() => setDomain(item)} className={`rounded-full px-3 py-1.5 text-xs font-bold ${domain === item ? "bg-[#1d382d] text-white" : "bg-[#e9e3d9] text-[#5c665c]"}`}>{item}</button>)}</div>
    <div className="grid gap-6 xl:grid-cols-[minmax(270px,.8fr)_minmax(0,1.8fr)]"><aside className="grid content-start gap-3 sm:grid-cols-2 xl:grid-cols-1">{visibleTracks.map(track => <button key={track.id} onClick={() => setActiveId(track.id)} className={`rounded-2xl border p-4 text-left transition ${active.id === track.id ? "border-[#1d382d] bg-[#1d382d] text-white" : "border-[#dfd8ce] bg-[#fffdf9] hover:border-[#a67b4e]"}`}><p className={`text-[10px] font-bold uppercase tracking-[.16em] ${active.id === track.id ? "text-[#d9b37d]" : "text-[#96724d]"}`}>{String(track.order).padStart(2, "0")} · {text(track.level, locale)}</p><h2 className="mt-2 font-serif text-xl leading-tight">{text(track.title, locale)}</h2><p className={`mt-2 text-xs leading-5 ${active.id === track.id ? "text-[#d0dbd0]" : "text-[#657064]"}`}>{text(track.domain, locale)}</p></button>)}</aside>
      <article className="rounded-3xl border border-[#dfd8ce] bg-[#fffdf9] p-5 md:p-7"><div className="flex flex-wrap items-start justify-between gap-3"><div><Tag tone="forest">{text(active.domain, locale)}</Tag><h1 className="mt-4 font-serif text-4xl leading-[1.02] md:text-5xl">{text(active.title, locale)}</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-[#59665b] md:text-base">{text(active.overview, locale)}</p></div><span className="rounded-full bg-[#eee6d8] px-3 py-1.5 text-xs font-bold text-[#5d492e]">{text(active.level, locale)}</span></div>
        <section className="mt-8"><h2 className="font-serif text-2xl">{ui.outcome}</h2><div className="mt-3 grid gap-2 md:grid-cols-3">{active.outcomes.map(item => <div key={text(item, locale)} className="flex gap-2 rounded-xl bg-[#f3eee6] p-3 text-sm leading-5 text-[#4d5b50]"><CheckCircle2 size={16} className="mt-0.5 shrink-0 text-[#2f6048]"/>{text(item, locale)}</div>)}</div></section>
        <section className="mt-8"><h2 className="font-serif text-2xl">{locale === "es" ? "Unidades aplicadas" : locale === "pt" ? "Unidades aplicadas" : "Applied units"}</h2><div className="mt-3 grid gap-3">{active.units.map((item, index) => <div key={text(item.title, locale)} className="rounded-2xl border border-[#e5ded3] p-4"><div className="flex gap-4"><span className="font-serif text-2xl text-[#b68350]">0{index + 1}</span><div><h3 className="font-semibold text-[#29382f]">{text(item.title, locale)}</h3><p className="mt-1 text-sm leading-6 text-[#626d64]">{text(item.objective, locale)}</p><p className="mt-3 border-l-2 border-[#d1a36f] pl-3 text-sm leading-6 text-[#4e5b50]">{text(item.practice, locale)}</p></div></div></div>)}</div></section>
        <section className="mt-8 grid gap-4 lg:grid-cols-2"><div className="rounded-2xl bg-[#1d382d] p-5 text-[#f8f4ec]"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#d7a15f]">{ui.studio}</p><p className="mt-3 font-serif text-xl leading-7">{text(active.studioBrief, locale)}</p><div className="mt-5 border-t border-white/15 pt-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-[#bcd0bd]">{ui.deliverable}</p><p className="mt-2 text-sm leading-6 text-[#e1e9df]">{text(active.deliverable, locale)}</p></div></div><div className="rounded-2xl bg-[#f3eee6] p-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-[#96724d]">{ui.guardrail}</p><p className="mt-3 text-sm leading-7 text-[#536055]">{text(active.guardrail, locale)}</p></div></section>
        <section className="mt-8"><h2 className="font-serif text-2xl">{ui.resources}</h2><div className="mt-3 grid gap-3 md:grid-cols-2">{active.resources.map(resource => <a key={resource.url} href={resource.url} target="_blank" rel="noreferrer" className="group rounded-2xl border border-[#dfd8ce] p-4 transition hover:-translate-y-0.5 hover:border-[#b98a58]"><div className="flex items-center justify-between gap-2"><Tag tone={resource.access === "open" ? "forest" : "neutral"}>{resource.access === "open" ? ui.open : ui.linked}</Tag><ExternalLink size={16} className="text-[#7d867c]"/></div><h3 className="mt-4 font-semibold text-[#29382f]">{resource.title}</h3><p className="mt-2 text-sm leading-6 text-[#657064]">{text(resource.note, locale)}</p><p className="mt-4 inline-flex items-center gap-1 text-xs font-bold text-[#80613f]">{resource.license}<ArrowUpRight size={13}/></p></a>)}</div></section>
      </article>
    </div>
  </>;
}
