import { useAuth } from "@/_core/hooks/useAuth";
import { startLogin } from "@/const";
import { useLocale } from "@/contexts/LocaleContext";
import { ui } from "@/lib/i18n";
import { ArrowDown, ArrowRight, ArrowUpRight, BookOpen, CheckCircle2, CircleDot, Compass, Globe2, LibraryBig, Play, ShieldCheck, Sparkles, Star, WandSparkles } from "lucide-react";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";
import { useRef } from "react";
import { Link } from "wouter";

gsap.registerPlugin(ScrollTrigger);

export default function Home() {
  const root = useRef<HTMLElement>(null);
  const { user } = useAuth();
  const { locale, setLocale } = useLocale();
  const copy = ui[locale];
  useGSAP(() => {
    const media = gsap.matchMedia();
    media.add("(prefers-reduced-motion: no-preference)", () => {
      const entrance = gsap.timeline({ defaults: { ease: "power3.out" } });
      entrance
        .from("[data-hero-nav]", { y: -14, opacity: 0, duration: 0.42 })
        .from("[data-hero-badge]", { y: 18, opacity: 0, duration: 0.42 }, "-=0.12")
        .from("[data-hero-title]", { y: 28, opacity: 0, duration: 0.62 }, "-=0.18")
        .from("[data-hero-description], [data-hero-actions], [data-hero-proof]", { y: 16, opacity: 0, duration: 0.38, stagger: 0.08 }, "-=0.25")
        .from("[data-hero-artifact]", { y: 32, opacity: 0, rotate: 1.5, duration: 0.68 }, "-=0.7");
      gsap.from("[data-method-card]", { scrollTrigger: { trigger: "#path", start: "top 78%" }, y: 28, opacity: 0, duration: 0.5, stagger: 0.1, ease: "power3.out" });
      gsap.from("[data-growth-panel]", { scrollTrigger: { trigger: "#growth", start: "top 78%" }, y: 34, opacity: 0, duration: 0.62, ease: "power3.out" });
    });
    return () => media.revert();
  }, { scope: root });
  const content = locale === "es" ? { eyebrow: "UX Academy · Growth Edition", lead: "Diseña, posiciona y demuestra", accent: "trabajo que merece ser encontrado.", desc: "Una experiencia trilingüe para convertir investigación, diseño, IA, crecimiento y criterio profesional en una práctica visible.", primary: user ? "Volver a mi estudio" : "Entrar al aula", secondary: "Ver el recorrido", discover: "Explorar Growth Studio", proof: ["17 módulos de UX/Product", "4 rutas de growth", "32 fuentes Google verificadas"], section: "No colecciones de teoría. Un sistema para avanzar.", sectionText: "Cada bloque hace visible el siguiente movimiento: comprender el problema, practicar un método y dejar evidencia de una decisión.", routes: "Rutas que construyen señal profesional", journey: "Tu bucle de aprendizaje" } : locale === "pt" ? { eyebrow: "UX Academy · Growth Edition", lead: "Projete, posicione e demonstre", accent: "trabalho que merece ser encontrado.", desc: "Uma experiência trilíngue para transformar pesquisa, design, IA, crescimento e critério profissional em prática visível.", primary: user ? "Voltar ao meu estúdio" : "Entrar na sala", secondary: "Ver o percurso", discover: "Explorar Growth Studio", proof: ["17 módulos de UX/Product", "4 trilhas de growth", "32 fontes Google verificadas"], section: "Não são coleções de teoria. É um sistema para avançar.", sectionText: "Cada bloco deixa claro o próximo movimento: compreender o problema, praticar um método e deixar evidência de uma decisão.", routes: "Trilhas que constroem sinal profissional", journey: "Seu ciclo de aprendizagem" } : { eyebrow: "UX Academy · Growth Edition", lead: "Design, position, and demonstrate", accent: "work worth being found.", desc: "A trilingual experience that turns research, design, AI, growth, and professional judgment into visible practice.", primary: user ? "Return to my studio" : "Enter the classroom", secondary: "See the path", discover: "Explore Growth Studio", proof: ["17 UX/Product modules", "4 growth pathways", "32 verified Google sources"], section: "Not a collection of theory. A system for moving forward.", sectionText: "Every block makes the next move visible: understand the problem, practice a method, and leave evidence of a decision.", routes: "Pathways that build professional signal", journey: "Your learning loop" };
  const cards = [{ icon: Compass, title: locale === "es" ? "Investiga" : locale === "pt" ? "Investigue" : "Investigate", text: locale === "es" ? "Convierte señales dispersas en preguntas defendibles." : locale === "pt" ? "Transforme sinais dispersos em perguntas defensáveis." : "Turn scattered signals into defensible questions.", tone: "bg-[#dcecff] text-[#123b83]" }, { icon: WandSparkles, title: locale === "es" ? "Construye" : locale === "pt" ? "Construa" : "Build", text: locale === "es" ? "Diseña flujos, interfaces y sistemas que se explican solos." : locale === "pt" ? "Desenhe fluxos, interfaces e sistemas que se explicam por si." : "Design flows, interfaces, and systems that explain themselves.", tone: "bg-[#e5f7de] text-[#17633b]" }, { icon: Star, title: locale === "es" ? "Hazlo visible" : locale === "pt" ? "Torne visível" : "Make it visible", text: locale === "es" ? "Presenta decisiones, experimentos y portfolio con criterio." : locale === "pt" ? "Apresente decisões, experimentos e portfólio com critério." : "Present decisions, experiments, and portfolio work with judgment.", tone: "bg-[#fff0cf] text-[#91450f]" }];
  return <main ref={root} className="min-h-screen overflow-hidden bg-[#fbfaf7] text-[#1c2340]"><header data-hero-nav className="relative z-20 mx-auto flex max-w-[1500px] items-center justify-between px-5 py-5 md:px-10"><Link href="/" className="flex items-center gap-3"><span className="grid h-10 w-10 place-items-center rounded-2xl bg-[#1d45a5] text-white shadow-[4px_4px_0_#ffd264]"><BookOpen size={19} /></span><span><span className="block font-serif text-xl leading-none">UX Academy</span><span className="mt-1 block text-[9px] font-bold uppercase tracking-[.17em] text-[#667296]">Growth Edition</span></span></Link><nav className="hidden items-center gap-6 text-sm font-medium text-[#4d5a7f] lg:flex"><a href="#path">{locale === "es" ? "Cómo funciona" : locale === "pt" ? "Como funciona" : "How it works"}</a><a href="#growth">{locale === "es" ? "Growth" : "Growth"}</a><Link href="/google-ecosystem">{locale === "es" ? "Ecosistema Google" : locale === "pt" ? "Ecossistema Google" : "Google ecosystem"}</Link></nav><div className="flex items-center gap-2 sm:gap-3"><select aria-label="Language" value={locale} onChange={event => setLocale(event.target.value as "es" | "pt" | "en")} className="rounded-xl border border-[#dbe0eb] bg-white px-2 py-2 text-xs font-bold text-[#30416f] shadow-sm"><option value="es">ES</option><option value="pt">PT</option><option value="en">EN</option></select>{user ? <Link href="/dashboard" className="rounded-xl bg-[#1d45a5] px-3 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-[#173b90] sm:px-4 sm:text-sm">{copy.dashboard}</Link> : <button onClick={() => startLogin()} className="rounded-xl bg-[#1d45a5] px-3 py-2 text-xs font-bold text-white shadow-sm transition hover:bg-[#173b90] sm:px-4 sm:text-sm">{copy.signIn}</button>}</div></header>
    <section className="relative isolate mx-auto max-w-[1500px] px-5 pb-20 pt-10 md:px-10 md:pb-28 md:pt-16"><div className="hero-grid pointer-events-none absolute inset-x-0 top-0 h-[680px] opacity-70"/><div aria-hidden="true" className="absolute left-[5%] top-[26%] h-16 w-16 rounded-full bg-[#ffd264] blur-[1px]"/><div aria-hidden="true" className="absolute right-[6%] top-[18%] h-24 w-24 rounded-[2rem] bg-[#f4b7df] blur-[1px]"/><div className="relative grid items-center gap-12 lg:grid-cols-[1.05fr_.95fr] lg:gap-20"><div className="relative z-10"><p data-hero-badge className="mb-7 inline-flex items-center gap-2 rounded-full border border-[#cfd9ed] bg-white/90 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.15em] text-[#38518d]"><CircleDot size={13} className="text-[#e34d90]"/>{content.eyebrow}</p><h1 data-hero-title className="max-w-4xl font-serif text-5xl leading-[.91] tracking-[-.06em] text-[#1b2445] sm:text-6xl lg:text-[5.8rem]"><span>{content.lead}</span><br/><span className="gradient-word">{content.accent}</span></h1><p data-hero-description className="mt-8 max-w-xl text-lg leading-8 text-[#516080]">{content.desc}</p><div data-hero-actions className="mt-9 flex flex-wrap gap-3"><button onClick={() => user ? window.location.assign("/dashboard") : startLogin()} className="inline-flex items-center gap-2 rounded-2xl bg-[#1d45a5] px-6 py-4 text-sm font-bold text-white shadow-[6px_6px_0_#ffcb54] transition hover:bg-[#173b90]">{content.primary}<ArrowUpRight size={17}/></button><a href="#path" className="inline-flex items-center gap-2 rounded-2xl border border-[#ccd5e6] bg-white px-6 py-4 text-sm font-bold text-[#34446f] transition hover:border-[#1d45a5]">{content.secondary}<ArrowDown size={17}/></a></div><div data-hero-proof className="mt-9 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-[#55627e]">{content.proof.map(item => <span key={item} className="flex items-center gap-1.5"><CheckCircle2 size={14} className="text-[#079b61]"/>{item}</span>)}</div><p data-hero-proof className="mt-6 flex max-w-xl items-center gap-2 text-xs leading-5 text-[#67748e]"><ShieldCheck size={15} className="shrink-0 text-[#2556be]" />{locale === "es" ? "Certificate of Completion interno. La plataforma no está afiliada ni certificada por Google." : locale === "pt" ? "Certificate of Completion interno. A plataforma não é afiliada nem certificada pelo Google." : "Internal Certificate of Completion. The platform is not affiliated with or certified by Google."}</p></div>
      <div data-hero-artifact className="relative mx-auto w-full max-w-[590px]"><div className="grain-surface relative overflow-hidden rounded-[2.5rem] border border-[#c7d4f1] bg-[#e9effd] p-4 shadow-[14px_18px_0_#ffcf63] sm:p-6"><div className="relative z-10 rounded-[2rem] bg-[#1d45a5] p-5 text-white sm:p-7"><div className="flex items-center justify-between"><span className="rounded-full bg-white/15 px-3 py-1 text-[10px] font-bold uppercase tracking-[.16em] text-[#dfe8ff]">{content.journey}</span><span className="grid h-9 w-9 place-items-center rounded-xl bg-[#ffd264] text-[#1d45a5]"><Sparkles size={17}/></span></div><div className="mt-7"><p className="text-sm font-medium text-[#cfdaff]">{locale === "es" ? "Hoy" : locale === "pt" ? "Hoje" : "Today"}</p><h2 className="mt-1 font-serif text-3xl leading-[1.04] sm:text-4xl">{locale === "es" ? "Convierte curiosidad en evidencia." : locale === "pt" ? "Transforme curiosidade em evidência." : "Turn curiosity into evidence."}</h2></div><div className="mt-7 grid gap-3 sm:grid-cols-3"><div className="rounded-2xl bg-white/12 p-3"><p className="font-mono text-[10px] text-[#bed0ff]">01 / FRAME</p><p className="mt-5 text-sm font-bold">{locale === "es" ? "Pregunta" : locale === "pt" ? "Pergunta" : "Question"}</p></div><div className="rounded-2xl bg-[#ffd264] p-3 text-[#1b3e91]"><p className="font-mono text-[10px] opacity-70">02 / PRACTICE</p><p className="mt-5 text-sm font-bold">{locale === "es" ? "Práctica" : locale === "pt" ? "Prática" : "Practice"}</p></div><div className="rounded-2xl bg-[#e6a2d1] p-3 text-[#58224d]"><p className="font-mono text-[10px] opacity-70">03 / SHOW</p><p className="mt-5 text-sm font-bold">{locale === "es" ? "Evidencia" : locale === "pt" ? "Evidência" : "Evidence"}</p></div></div><div className="mt-6 rounded-2xl border border-white/15 bg-[#143681] p-4"><div className="flex items-center justify-between text-xs text-[#d9e4ff]"><span>{locale === "es" ? "Siguiente desbloqueo" : locale === "pt" ? "Próximo desbloqueio" : "Next unlock"}</span><span className="font-bold text-[#ffd264]">75%</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-3/4 rounded-full bg-[#54d39d]"/></div><p className="mt-3 text-sm font-medium">{locale === "es" ? "Práctica guiada: decidir con señales de Search Console" : locale === "pt" ? "Prática guiada: decidir com sinais do Search Console" : "Guided practice: decide with Search Console signals"}</p></div></div></div><div aria-hidden="true" className="orbit-dot absolute -bottom-5 -left-4 grid h-16 w-16 place-items-center rounded-3xl bg-[#75dfbc] text-[#10563b] shadow-sm"><Play size={23} fill="currentColor"/></div><div aria-hidden="true" className="orbit-dot absolute -right-3 top-[22%] grid h-14 w-14 place-items-center rounded-full bg-[#f2a2ce] text-[#852952]"><ArrowRight size={24}/></div></div></div></section>
    <section id="path" className="border-y border-[#dde2ee] bg-white py-20 md:py-28"><div className="mx-auto max-w-[1500px] px-5 md:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#3155a7]">UX Academy method</p><h2 className="mt-4 max-w-md font-serif text-4xl leading-[1.02] tracking-[-.04em] text-[#1b2445] md:text-5xl">{content.section}</h2><p className="mt-5 max-w-md text-base leading-7 text-[#596684]">{content.sectionText}</p><Link href="/growth" className="mt-7 inline-flex items-center gap-2 text-sm font-bold text-[#1d45a5] underline decoration-[#ffd264] decoration-4 underline-offset-4">{content.discover}<ArrowUpRight size={16}/></Link></div><div className="grid gap-4 md:grid-cols-3">{cards.map(card => { const Icon = card.icon; return <article data-method-card key={card.title} className={`rounded-[1.75rem] p-5 ${card.tone}`}><span className="grid h-10 w-10 place-items-center rounded-2xl bg-white/70 shadow-sm"><Icon size={20}/></span><h3 className="mt-12 font-serif text-2xl leading-none">{card.title}</h3><p className="mt-4 text-sm leading-6 opacity-80">{card.text}</p><span className="mt-7 inline-flex items-center gap-1 text-xs font-bold uppercase tracking-[.13em]">{String(cards.indexOf(card) + 1).padStart(2, "0")}<ArrowRight size={14}/></span></article>; })}</div></div></div></section>
    <section id="growth" className="mx-auto max-w-[1500px] px-5 py-20 md:px-10 md:py-28"><div data-growth-panel className="overflow-hidden rounded-[2.4rem] bg-[#202a51] px-6 py-10 text-white md:px-10 md:py-14"><div className="grid items-end gap-8 lg:grid-cols-[1fr_.8fr]"><div><p className="text-xs font-bold uppercase tracking-[.18em] text-[#a9c1ff]">Growth, content & discovery</p><h2 className="mt-4 max-w-2xl font-serif text-4xl leading-[1.03] tracking-[-.04em] md:text-5xl">{content.routes}</h2><p className="mt-5 max-w-xl text-base leading-7 text-[#c9d4f3]">{locale === "es" ? "SEO, marketing responsable, marca audiovisual y Research Ops con IA: rutas originales, fuentes atribuidas y una práctica que se puede mostrar." : locale === "pt" ? "SEO, marketing responsável, marca audiovisual e Research Ops com IA: trilhas originais, fontes atribuídas e uma prática que pode ser mostrada." : "SEO, responsible marketing, audiovisual brand, and AI Research Ops: original paths, attributed sources, and practice you can show."}</p></div><div className="grid gap-3 sm:grid-cols-2">{["SEO / Content", "Marketing / Conversion", "Video / Brand", "Research Ops / AI"].map((route, index) => <div key={route} className="rounded-2xl border border-white/10 bg-white/7 p-4"><p className="font-mono text-[10px] text-[#a9c1ff]">0{index + 1}</p><p className="mt-8 font-serif text-xl">{route}</p></div>)}</div></div><div className="mt-10 flex flex-wrap items-center justify-between gap-5 border-t border-white/15 pt-6"><p className="max-w-2xl text-sm leading-6 text-[#bdc9e8]">{locale === "es" ? "Incluye curaduría de canales y playlists de fuente original. UX Academy enlaza: no descarga ni re-publica contenido de terceros." : locale === "pt" ? "Inclui curadoria de canais e playlists da fonte original. UX Academy vincula: não baixa nem republica conteúdo de terceiros." : "Includes curated original-source channels and playlists. UX Academy links to—never downloads or republishes—third-party content."}</p><Link href="/google-ecosystem" className="inline-flex items-center gap-2 rounded-2xl bg-[#ffd264] px-5 py-3 text-sm font-bold text-[#192653] transition hover:bg-[#ffe093]"><LibraryBig size={17}/>{content.discover}</Link></div></div></section>
  </main>;
}
