import { t, type Localized } from "./courseContent";

export type RubricLevel = "novice" | "competent" | "advanced" | "professional";

export type Rubric = {
  id: string;
  title: Localized;
  criterion: Localized;
  levels: Record<RubricLevel, Localized>;
};

const rubric = (id: string, title: Localized, criterion: Localized, novice: Localized, competent: Localized, advanced: Localized, professional: Localized): Rubric => ({
  id, title, criterion, levels: { novice, competent, advanced, professional },
});

export const rubrics: Rubric[] = [
  rubric("ai", t("UX + IA", "UX + IA", "UX + AI"), t("Usa IA con alcance explícito, minimización de datos, supervisión humana y trazabilidad.", "Usa IA com escopo explícito, minimização de dados, supervisão humana e rastreabilidade.", "Uses AI with explicit scope, data minimization, human oversight, and traceability."), t("Acepta salidas generadas como hechos o incluye datos sensibles sin evaluar riesgo.", "Aceita saídas geradas como fatos ou inclui dados sensíveis sem avaliar risco.", "Accepts generated outputs as fact or includes sensitive data without risk assessment."), t("Declara una tarea apta y revisa al menos la consistencia básica de la salida.", "Declara uma tarefa adequada e revisa ao menos a consistência básica da saída.", "States a suitable task and reviews basic output consistency."), t("Contrasta la salida con fuentes, registra límites, evalúa sesgo y conserva una decisión humana explícita.", "Confronta a saída com fontes, registra limites, avalia viés e preserva decisão humana explícita.", "Compares output with sources, records limits, assesses bias, and preserves explicit human decision."), t("Diseña experiencias de IA que comunican incertidumbre, control, privacidad y alternativas, y que se someten a evaluación inclusiva.", "Desenha experiências de IA que comunicam incerteza, controle, privacidade e alternativas, e que são submetidas a avaliação inclusiva.", "Designs AI experiences that communicate uncertainty, control, privacy, and alternatives and undergo inclusive evaluation.")),
  rubric("research", t("Investigación", "Pesquisa", "Research"), t("Selecciona, ejecuta y sintetiza métodos proporcionales a una decisión.", "Seleciona, executa e sintetiza métodos proporcionais a uma decisão.", "Selects, conducts, and synthesizes methods proportional to a decision."), t("Confunde opiniones con evidencia y usa métodos sin una pregunta concreta.", "Confunde opiniões com evidências e usa métodos sem uma pergunta concreta.", "Confuses opinions with evidence and uses methods without a specific question."), t("Define preguntas útiles y documenta evidencia básica, aunque con limitaciones explícitas.", "Define perguntas úteis e documenta evidências básicas, embora com limitações explícitas.", "Defines useful questions and documents basic evidence, with explicit limitations."), t("Triangula métodos, reconoce sesgos y conecta hallazgos con decisiones priorizadas.", "Triangula métodos, reconhece vieses e conecta achados a decisões priorizadas.", "Triangulates methods, recognizes bias, and connects findings to prioritized decisions."), t("Diseña investigación ética y sostenible que modifica estrategia, producto y aprendizaje del equipo.", "Desenha pesquisa ética e sustentável que modifica estratégia, produto e aprendizagem da equipe.", "Designs ethical, sustainable research that changes strategy, product, and team learning.")),
  rubric("problem", t("Definición del problema", "Definição do problema", "Problem definition"), t("Formula oportunidades que conservan la incertidumbre y la conexión con evidencia.", "Formula oportunidades que preservam a incerteza e a conexão com evidências.", "Frames opportunities that preserve uncertainty and connection to evidence."), t("Presenta una solución como si fuera el problema.", "Apresenta uma solução como se fosse o problema.", "Presents a solution as though it were the problem."), t("Describe usuario, contexto y necesidad con una hipótesis explícita.", "Descreve usuário, contexto e necessidade com uma hipótese explícita.", "Describes user, context, and need with an explicit hypothesis."), t("Diferencia síntoma, oportunidad y criterio de éxito; propone alternativas evaluables.", "Diferencia sintoma, oportunidade e critério de sucesso; propõe alternativas avaliáveis.", "Distinguishes symptom, opportunity, and success criterion; proposes evaluable alternatives."), t("Enmarca tensiones complejas, negocia trade-offs y alinea actores en un outcome verificable.", "Enquadra tensões complexas, negocia trade-offs e alinha atores em um outcome verificável.", "Frames complex tensions, negotiates trade-offs, and aligns stakeholders around a testable outcome.")),
  rubric("ia", t("Arquitectura de información", "Arquitetura da informação", "Information architecture"), t("Organiza contenido según tareas y modelos mentales de las personas.", "Organiza conteúdo conforme tarefas e modelos mentais das pessoas.", "Organizes content around people’s tasks and mental models."), t("Replica una estructura interna o mezcla categorías sin criterio.", "Replica uma estrutura interna ou mistura categorias sem critério.", "Replicates internal structure or mixes categories without rationale."), t("Crea categorías y etiquetas comprensibles para tareas principales.", "Cria categorias e rótulos compreensíveis para tarefas principais.", "Creates understandable categories and labels for primary tasks."), t("Valida encontrabilidad, busca y navegación con tareas y evidencia.", "Valida encontrabilidade, busca e navegação com tarefas e evidências.", "Validates findability, search, and navigation with tasks and evidence."), t("Diseña arquitecturas coherentes entre canales, escalables y gobernadas con evidencia continua.", "Desenha arquiteturas coerentes entre canais, escaláveis e governadas com evidência contínua.", "Designs cross-channel, scalable architectures governed by ongoing evidence.")),
  rubric("wireframes", t("Wireframes", "Wireframes", "Wireframes"), t("Comunica estructura, secuencia, prioridades y estados antes de la alta fidelidad.", "Comunica estrutura, sequência, prioridades e estados antes da alta fidelidade.", "Communicates structure, sequence, priorities, and states before high fidelity."), t("Dibuja pantallas aisladas o solo el camino ideal.", "Desenha telas isoladas ou apenas o caminho ideal.", "Draws isolated screens or only the ideal path."), t("Representa la tarea principal y anota las decisiones esenciales.", "Representa a tarefa principal e anota decisões essenciais.", "Represents the primary task and annotates essential decisions."), t("Cubre bifurcaciones, estados de recuperación y supuestos que deben probarse.", "Cobre bifurcações, estados de recuperação e suposições que devem ser testadas.", "Covers branches, recovery states, and assumptions requiring testing."), t("Usa fidelidad estratégicamente para reducir riesgo y alinear producto, investigación e ingeniería.", "Usa fidelidade estrategicamente para reduzir risco e alinhar produto, pesquisa e engenharia.", "Uses fidelity strategically to reduce risk and align product, research, and engineering.")),
  rubric("ui", t("UI Design", "UI Design", "UI Design"), t("Construye jerarquía, sistema visual y contenido que apoyan una tarea clara.", "Constrói hierarquia, sistema visual e conteúdo que apoiam uma tarefa clara.", "Builds hierarchy, visual system, and content that support a clear task."), t("Prioriza decoración o tendencias sobre comprensión y comportamiento.", "Prioriza decoração ou tendências em vez de compreensão e comportamento.", "Prioritizes decoration or trends over comprehension and behavior."), t("Aplica tipografía, espacio, contraste y componentes de manera consistente.", "Aplica tipografia, espaço, contraste e componentes de modo consistente.", "Applies type, space, contrast, and components consistently."), t("Diseña estados, feedback y contenido con intención y los relaciona con evidencia de uso.", "Desenha estados, feedback e conteúdo com intenção e os relaciona com evidências de uso.", "Designs states, feedback, and content intentionally and relates them to usage evidence."), t("Crea sistemas visuales expresivos y mantenibles que elevan comprensión sin sacrificar inclusión.", "Cria sistemas visuais expressivos e sustentáveis que elevam compreensão sem sacrificar inclusão.", "Creates expressive, maintainable visual systems that improve comprehension without sacrificing inclusion.")),
  rubric("accessibility", t("Accesibilidad", "Acessibilidade", "Accessibility"), t("Previene y evalúa barreras perceptivas, operativas, cognitivas y técnicas.", "Previne e avalia barreiras perceptivas, operacionais, cognitivas e técnicas.", "Prevents and evaluates perceptual, operational, cognitive, and technical barriers."), t("Trata accesibilidad como un ajuste cosmético o revisión final.", "Trata acessibilidade como ajuste cosmético ou revisão final.", "Treats accessibility as cosmetic adjustment or final review."), t("Incluye contraste, foco visible, labels y alternativas básicas.", "Inclui contraste, foco visível, labels e alternativas básicas.", "Includes contrast, visible focus, labels, and basic alternatives."), t("Prueba con teclado, tecnologías de asistencia y escenarios diversos; documenta correcciones.", "Testa com teclado, tecnologias assistivas e cenários diversos; documenta correções.", "Tests with keyboard, assistive tech, and diverse scenarios; documents fixes."), t("Integra inclusión en investigación, estrategia, sistema de diseño, QA y métricas de calidad.", "Integra inclusão em pesquisa, estratégia, sistema de design, QA e métricas de qualidade.", "Integrates inclusion into research, strategy, design system, QA, and quality metrics.")),
  rubric("responsive", t("Responsive & Mobile UX", "Responsive & Mobile UX", "Responsive & Mobile UX"), t("Preserva objetivos y autonomía adaptando jerarquía, navegación, entrada y estados a cada contexto.", "Preserva objetivos e autonomia adaptando hierarquia, navegação, entrada e estados a cada contexto.", "Preserves goals and autonomy by adapting hierarchy, navigation, input, and states to each context."), t("Reduce una pantalla de escritorio sin reconsiderar prioridades ni interacción.", "Reduz uma tela desktop sem reconsiderar prioridades ou interação.", "Shrinks a desktop screen without reconsidering priorities or interaction."), t("Documenta cambios básicos de reflujo y tamaño en móvil y escritorio.", "Documenta mudanças básicas de reflow e tamanho em celular e desktop.", "Documents basic reflow and size changes on mobile and desktop."), t("Define comportamiento por breakpoints, conserva trabajo ante interrupciones y prueba la tarea en múltiples tamaños.", "Define comportamento por breakpoints, preserva trabalho diante de interrupções e testa a tarefa em múltiplos tamanhos.", "Defines breakpoint behavior, preserves work through interruptions, and tests the task across sizes."), t("Diseña una estrategia adaptativa basada en contexto de uso, conectividad, entrada y necesidades diversas, con especificación lista para desarrollo.", "Desenha uma estratégia adaptativa baseada em contexto de uso, conectividade, entrada e necessidades diversas, com especificação pronta para desenvolvimento.", "Designs an adaptive strategy based on context, connectivity, input, and diverse needs, with development-ready specification.")),
  rubric("testing", t("Usability Testing", "Usability Testing", "Usability Testing"), t("Observa tareas realistas y produce iteraciones basadas en evidencia.", "Observa tarefas realistas e produz iterações baseadas em evidências.", "Observes realistic tasks and produces evidence-based iterations."), t("Hace preguntas inductivas o confunde comentarios con hallazgos.", "Faz perguntas indutivas ou confunde comentários com achados.", "Asks leading questions or confuses comments with findings."), t("Escribe tareas claras y distingue observación de interpretación.", "Escreve tarefas claras e distingue observação de interpretação.", "Writes clear tasks and distinguishes observation from interpretation."), t("Prioriza hallazgos por impacto, evidencia y riesgo; reitera el diseño con trazabilidad.", "Prioriza achados por impacto, evidência e risco; itera o design com rastreabilidade.", "Prioritizes findings by impact, evidence, and risk; iterates with traceability."), t("Orquesta investigación continua con decisiones, métricas y comunicación de incertidumbre.", "Orquestra pesquisa contínua com decisões, métricas e comunicação de incerteza.", "Orchestrates continuous research with decisions, metrics, and uncertainty communication.")),
  rubric("documentation", t("Documentación y handoff", "Documentação e handoff", "Documentation and handoff"), t("Explica comportamiento, decisiones, estados y restricciones para que otros puedan actuar.", "Explica comportamento, decisões, estados e restrições para que outras pessoas possam agir.", "Explains behavior, decisions, states, and constraints so others can act."), t("Entrega pantallas sin reglas, contexto ni dueños.", "Entrega telas sem regras, contexto ou responsáveis.", "Delivers screens without rules, context, or owners."), t("Documenta componentes, acciones y estados principales.", "Documenta componentes, ações e estados principais.", "Documents primary components, actions, and states."), t("Incluye casos límite, responsive, accesibilidad y decisiones abiertas con responsables.", "Inclui casos limite, responsividade, acessibilidade e decisões abertas com responsáveis.", "Includes edge cases, responsive behavior, accessibility, and open decisions with owners."), t("Crea una fuente de verdad mantenible que acelera colaboración y preserva el contexto de decisiones.", "Cria uma fonte de verdade sustentável que acelera colaboração e preserva o contexto das decisões.", "Creates a maintainable source of truth that accelerates collaboration and preserves decision context.")),
  rubric("portfolio", t("Portfolio y presentación", "Portfólio e apresentação", "Portfolio and presentation"), t("Comunica contribución, razonamiento, evidencia, resultado y aprendizaje de manera honesta.", "Comunica contribuição, raciocínio, evidências, resultado e aprendizagem de forma honesta.", "Communicates contribution, reasoning, evidence, result, and learning honestly."), t("Muestra pantallas sin problema, rol, evidencia ni reflexión.", "Mostra telas sem problema, papel, evidências ou reflexão.", "Shows screens without problem, role, evidence, or reflection."), t("Narra contexto, papel, proceso y resultado con claridad.", "Narra contexto, papel, processo e resultado com clareza.", "Narrates context, role, process, and result clearly."), t("Conecta decisiones con evidencia, declara límites y responde preguntas con precisión.", "Conecta decisões com evidências, declara limites e responde perguntas com precisão.", "Connects decisions to evidence, states limits, and answers questions precisely."), t("Presenta casos memorables, accesibles y rigurosos que demuestran pensamiento de producto y madurez profesional.", "Apresenta casos memoráveis, acessíveis e rigorosos que demonstram pensamento de produto e maturidade profissional.", "Presents memorable, accessible, rigorous cases that demonstrate product thinking and professional maturity.")),
];

export type PracticeCase = {
  id: string;
  moduleId: string;
  level: Localized;
  title: Localized;
  prompt: Localized;
  successSignals: Localized[];
  firstHint: Localized;
  possibleApproach: Localized;
};

export const practiceCases: PracticeCase[] = [
  { id: "checkout", moduleId: "foundations", level: t("Fundamentos", "Fundamentos", "Foundations"), title: t("Abandono en checkout", "Abandono no checkout", "Checkout abandonment"), prompt: t("Una tienda observa abandono del 60 % al confirmar compra. ¿Qué investigarías antes de proponer cambios? Explica decisión, evidencia, método y límites.", "Uma loja observa abandono de 60% ao confirmar compra. O que você investigaria antes de propor mudanças? Explique decisão, evidência, método e limites.", "A store sees 60% abandonment at purchase confirmation. What would you investigate before proposing changes? Explain decision, evidence, method, and limits."), successSignals: [t("Separa síntoma e hipótesis", "Separa sintoma e hipótese", "Separates symptom and hypothesis"), t("Combina fuentes sin sobregeneralizar", "Combina fontes sem generalizar demais", "Combines sources without overgeneralizing")], firstHint: t("Piensa qué puede mostrar el comportamiento agregado y qué requiere observar una tarea concreta.", "Pense no que o comportamento agregado pode mostrar e no que exige observar uma tarefa concreta.", "Consider what aggregate behavior can show and what requires observing a concrete task."), possibleApproach: t("Primero definiría en qué punto y para qué segmentos ocurre el abandono; revisaría eventos y errores disponibles, y después observaría tareas representativas con una guía neutral. Evitaría concluir que el precio o un botón son la causa antes de contrastar evidencia.", "Primeiro definiria em que ponto e para quais segmentos ocorre o abandono; revisaria eventos e erros disponíveis e depois observaria tarefas representativas com um roteiro neutro. Evitaria concluir que preço ou botão são a causa antes de confrontar evidências.", "I would first define where and for which segments abandonment happens; review available events and errors; then observe representative tasks with a neutral script. I would avoid concluding price or a button is the cause before testing evidence.") },
  { id: "settings", moduleId: "information-architecture", level: t("Intermedio", "Intermediário", "Intermediate"), title: t("Configuración imposible de encontrar", "Configuração impossível de encontrar", "Impossible-to-find settings"), prompt: t("Los usuarios no encuentran ajustes de privacidad. Propón cómo distinguir un problema de IA, etiqueta, navegación o acceso contextual.", "Usuários não encontram configurações de privacidade. Proponha como distinguir um problema de IA, rótulo, navegação ou acesso contextual.", "Users cannot find privacy settings. Propose how to distinguish an IA, label, navigation, or contextual-access problem."), successSignals: [t("Formula hipótesis competidoras", "Formula hipóteses concorrentes", "Formulates competing hypotheses"), t("Propone prueba de encontrabilidad", "Propõe teste de encontrabilidade", "Proposes a findability test")], firstHint: t("Aísla la estructura del aspecto visual antes de rediseñar toda la pantalla.", "Isole a estrutura do aspecto visual antes de redesenhar toda a tela.", "Isolate structure from visual styling before redesigning the whole screen."), possibleApproach: t("Usaría un tree test para explorar arquitectura y etiquetas, compararía rutas de navegación y realizaría tareas de prueba sin mencionar el nombre del ajuste. Si las personas encuentran la rama pero dudan, investigaría la etiqueta; si ni siquiera llegan, revisaría la jerarquía.", "Usaria um tree test para explorar arquitetura e rótulos, compararia rotas de navegação e realizaria tarefas sem mencionar o nome da configuração. Se as pessoas encontrarem o ramo mas hesitarem, investigaria o rótulo; se nem chegarem, revisaria a hierarquia.", "I would use a tree test to explore architecture and labels, compare navigation paths, and run tasks without naming the setting. If people reach the branch but hesitate, I would investigate the label; if they never reach it, I would revisit hierarchy.") },
  { id: "form-errors", moduleId: "accessibility", level: t("Avanzado", "Avançado", "Advanced"), title: t("Errores de formulario", "Erros de formulário", "Form errors"), prompt: t("Una aplicación recibe múltiples reintentos de formulario en móvil. Diseña una investigación y una intervención que contemple accesibilidad, conectividad y recuperación.", "Um aplicativo recebe várias novas tentativas de formulário no celular. Desenhe uma pesquisa e intervenção que considere acessibilidade, conectividade e recuperação.", "An app receives multiple mobile form retries. Design research and intervention that considers accessibility, connectivity, and recovery."), successSignals: [t("Incluye estados y recuperación", "Inclui estados e recuperação", "Includes states and recovery"), t("Considera teclado y foco", "Considera teclado e foco", "Considers keyboard and focus")], firstHint: t("No supongas que cada reintento es un error de validación; puede ser red, foco, comprensión o pérdida de información.", "Não suponha que cada nova tentativa seja erro de validação; pode ser rede, foco, compreensão ou perda de informação.", "Do not assume every retry is validation failure; it may be network, focus, comprehension, or lost information."), possibleApproach: t("Revisaría la secuencia de eventos y los mensajes de error, observaría tareas en condiciones móviles y probaría teclado, lector de pantalla y red degradada. La intervención preservaría datos, resumiría errores con foco manejado y permitiría reintentar sin volver a empezar.", "Revisaria a sequência de eventos e mensagens de erro, observaria tarefas em condições móveis e testaria teclado, leitor de tela e rede degradada. A intervenção preservaria dados, resumiria erros com foco gerenciado e permitiria tentar novamente sem recomeçar.", "I would review event sequence and error messages, observe tasks in mobile conditions, and test keyboard, screen reader, and degraded network. The intervention would preserve data, summarize errors with managed focus, and allow retry without starting over.") },
];

export type FinalExamQuestion = {
  id: string;
  domain: Localized;
  prompt: Localized;
  expected: Localized;
};

export const finalExam: FinalExamQuestion[] = [
  { id: "fe-research", domain: t("Research", "Pesquisa", "Research"), prompt: t("Una métrica cae después de un rediseño. Describe la secuencia de investigación antes de decidir revertir o escalar.", "Uma métrica cai depois de um redesign. Descreva a sequência de pesquisa antes de decidir reverter ou escalar.", "A metric falls after a redesign. Describe the research sequence before deciding to revert or scale."), expected: t("Distingue segmentos, instrumentación, evidencia cualitativa, hipótesis y guardrails.", "Distingue segmentos, instrumentação, evidências qualitativas, hipóteses e guardrails.", "Distinguishes segments, instrumentation, qualitative evidence, hypotheses, and guardrails.") },
  { id: "fe-ia", domain: t("Information Architecture", "Arquitetura da informação", "Information Architecture"), prompt: t("Un área de ayuda tiene muchas categorías internas. Propón un plan para validarlas con usuarios.", "Uma área de ajuda tem muitas categorias internas. Proponha um plano para validá-las com usuários.", "A help area has many internal categories. Propose a plan to validate them with users."), expected: t("Incluye inventario, card sort o tree test, tareas, criterios de éxito y revisión de etiquetas.", "Inclui inventário, card sort ou tree test, tarefas, critérios de sucesso e revisão de rótulos.", "Includes inventory, card sort or tree test, tasks, success criteria, and label review.") },
  { id: "fe-accessibility", domain: t("Accessibility", "Acessibilidade", "Accessibility"), prompt: t("Explica cómo evaluarías un componente de alerta para teclado, lector de pantalla y cognición.", "Explique como avaliaria um componente de alerta para teclado, leitor de tela e cognição.", "Explain how you would evaluate an alert component for keyboard, screen reader, and cognition."), expected: t("Cubre foco, anuncio, semántica, contraste, texto claro, cierre y retorno de contexto.", "Cobre foco, anúncio, semântica, contraste, texto claro, fechamento e retorno de contexto.", "Covers focus, announcement, semantics, contrast, clear text, dismissal, and context return.") },
  { id: "fe-product", domain: t("Product Design", "Product Design", "Product Design"), prompt: t("Transforma 'añadir recomendaciones con IA' en una hipótesis de producto responsable.", "Transforme 'adicionar recomendações com IA' em uma hipótese de produto responsável.", "Turn 'add AI recommendations' into a responsible product hypothesis."), expected: t("Declara usuario, outcome, supuesto, señal de éxito, daño posible, supervisión y prueba proporcional.", "Declara usuário, outcome, suposição, sinal de sucesso, dano possível, supervisão e teste proporcional.", "States user, outcome, assumption, success signal, possible harm, oversight, and proportional test.") },
  { id: "fe-portfolio", domain: t("Portfolio", "Portfólio", "Portfolio"), prompt: t("Escribe el esquema de un caso de estudio que demuestre decisión y aprendizaje, no solo resultado visual.", "Escreva o esquema de um estudo de caso que demonstre decisão e aprendizagem, não apenas resultado visual.", "Write an outline for a case study showing decision and learning, not merely visual output."), expected: t("Incluye contexto, rol, evidencia, decisiones, iteración, resultados, límites y reflexión.", "Inclui contexto, papel, evidências, decisões, iteração, resultados, limites e reflexão.", "Includes context, role, evidence, decisions, iteration, results, limits, and reflection.") },
];

export const certificateRules = {
  lessonCompletion: 100,
  minimumProgramScore: 70,
  minimumFinalExam: 70,
  requiredProjects: 4,
  capstoneMinimumLevel: "competent" as RubricLevel,
  title: t("Certificate of Completion — UX Design Professional Program", "Certificate of Completion — UX Design Professional Program", "Certificate of Completion — UX Design Professional Program"),
  disclaimer: t("Reconocimiento interno de finalización. No es una certificación oficial de Google ni una acreditación académica.", "Reconhecimento interno de conclusão. Não é uma certificação oficial do Google nem uma acreditação acadêmica.", "Internal completion recognition. It is not an official Google certification or an academic credential."),
};
