import { t, type Localized } from "./courseContent";

export type GrowthLesson = {
  id: string;
  title: Localized;
  objective: Localized;
  concepts: Localized[];
  commonMistake: Localized;
  guidedPractice: Localized;
  independentPractice: Localized;
};

export type GrowthTrack = {
  id: string;
  order: number;
  title: Localized;
  label: Localized;
  overview: Localized;
  outcomes: Localized[];
  lessons: GrowthLesson[];
  portfolioBrief: Localized;
  deliverable: Localized;
  rubric: { criterion: Localized; evidence: Localized }[];
  resourceIds: string[];
};

export type VideoResource = {
  id: string;
  title: string;
  publisher: string;
  url: string;
  format: "channel" | "playlist" | "course" | "video" | "documentation";
  level: "foundation" | "intermediate" | "advanced";
  topics: string[];
  language: "en" | "es" | "multilingual";
  access: "public-link" | "open-documentation";
  note: Localized;
  why: Localized;
};

const lesson = (id: string, title: Localized, objective: Localized, concepts: Localized[], commonMistake: Localized, guidedPractice: Localized, independentPractice: Localized): GrowthLesson => ({ id, title, objective, concepts, commonMistake, guidedPractice, independentPractice });

export const growthTracks: GrowthTrack[] = [
  {
    id: "seo-content-systems", order: 1, label: t("SEO y contenido útil", "SEO e conteúdo útil", "SEO and helpful content"), title: t("De intención de búsqueda a una arquitectura que sirve", "Da intenção de busca a uma arquitetura que serve", "From search intent to an architecture that serves"),
    overview: t("Una ruta de SEO centrada en personas: entiende la necesidad, crea una respuesta original, hazla accesible y mide con humildad.", "Uma trilha de SEO centrada nas pessoas: entenda a necessidade, crie uma resposta original, torne-a acessível e meça com humildade.", "A people-centered SEO pathway: understand the need, create an original answer, make it accessible, and measure with humility."),
    outcomes: [t("Traducir una consulta en una necesidad y una tarea", "Traduzir uma consulta em uma necessidade e uma tarefa", "Translate a query into a need and task"), t("Diseñar una estructura de contenido que se pueda explorar", "Desenhar uma estrutura de conteúdo explorável", "Design an explorable content structure"), t("Priorizar con evidencia de usuario, búsqueda y rendimiento", "Priorizar com evidência de usuário, busca e desempenho", "Prioritize with user, search, and performance evidence")],
    lessons: [
      lesson("intent", t("Intención, contexto y trabajo por resolver", "Intenção, contexto e trabalho a resolver", "Intent, context, and jobs to be done"), t("Distingue palabras clave de la situación humana que lleva a una persona a buscar.", "Diferencie palavras-chave da situação humana que leva uma pessoa a pesquisar.", "Distinguish keywords from the human situation that brings a person to search."), [t("Consulta ≠ intención", "Consulta ≠ intenção", "Query ≠ intent"), t("Tarea, ansiedad y criterio de éxito", "Tarefa, ansiedade e critério de sucesso", "Task, anxiety, and success criterion"), t("Segmentos de conocimiento, no estereotipos", "Segmentos de conhecimento, não estereótipos", "Knowledge segments, not stereotypes")], t("Agrupar consultas solo por volumen y olvidar qué espera resolver la persona.", "Agrupar consultas apenas por volume e esquecer o que a pessoa espera resolver.", "Grouping queries only by volume and forgetting what the person expects to solve."), t("Toma cinco consultas sobre una decisión de producto y escribe la tarea, duda y evidencia que una página debería ofrecer.", "Escolha cinco consultas sobre uma decisão de produto e escreva a tarefa, dúvida e evidência que uma página deveria oferecer.", "Take five queries about a product decision and write the task, doubt, and evidence a page should offer."), t("Crea un mapa de intención para una academia ficticia, con al menos una ruta de descubrimiento, comparación y acción.", "Crie um mapa de intenção para uma academia fictícia, com pelo menos uma rota de descoberta, comparação e ação.", "Create an intent map for a fictitious academy with at least one discovery, comparison, and action path.")),
      lesson("architecture", t("Arquitectura de información que se descubre", "Arquitetura da informação que se descobre", "Information architecture that gets discovered"), t("Organiza rutas, títulos, enlaces y páginas para que una persona y un buscador entiendan su relación.", "Organize rotas, títulos, links e páginas para que uma pessoa e um buscador entendam sua relação.", "Organize paths, titles, links, and pages so a person and a search engine understand their relationship."), [t("Agrupación temática", "Agrupamento temático", "Topical grouping"), t("Navegación y enlaces descriptivos", "Navegação e links descritivos", "Navigation and descriptive links"), t("URL canónica y propósito único", "URL canônica e propósito único", "Canonical URL and single purpose")], t("Crear muchas páginas similares que compiten entre sí y no ayudan a elegir.", "Criar muitas páginas semelhantes que competem entre si e não ajudam a escolher.", "Creating many similar pages that compete with each other and do not help people choose."), t("Convierte un inventario de 12 artículos en un mapa de temas, hubs y enlaces que expliquen por qué cada página existe.", "Converta um inventário de 12 artigos em um mapa de temas, hubs e links que expliquem por que cada página existe.", "Turn an inventory of 12 articles into a map of topics, hubs, and links explaining why each page exists."), t("Diseña la navegación de una biblioteca de aprendizaje con tres niveles y justifica cada etiqueta.", "Desenhe a navegação de uma biblioteca de aprendizagem com três níveis e justifique cada rótulo.", "Design navigation for a learning library with three levels and justify every label.")),
      lesson("on-page", t("Página útil, legible y accesible", "Página útil, legível e acessível", "Useful, readable, accessible pages"), t("Redacta títulos, resúmenes, medios y llamadas a la acción que informan en lugar de manipular.", "Escreva títulos, resumos, mídias e chamadas à ação que informam em vez de manipular.", "Write titles, summaries, media, and calls to action that inform instead of manipulate."), [t("Promesa precisa", "Promessa precisa", "Precise promise"), t("Jerarquía escaneable", "Hierarquia escaneável", "Scannable hierarchy"), t("Alt, transcripción y contexto de medios", "Alt, transcrição e contexto de mídia", "Alt text, transcript, and media context")], t("Repetir la misma frase objetivo hasta que el texto pierda sentido y valor.", "Repetir a mesma frase-alvo até que o texto perca sentido e valor.", "Repeating the same target phrase until the text loses meaning and value."), t("Edita una introducción de 180 palabras para que responda a una pregunta, declare límites y permita escanear su contenido.", "Edite uma introdução de 180 palavras para que responda a uma pergunta, declare limites e permita escanear o conteúdo.", "Edit a 180-word introduction so it answers a question, states limits, and can be scanned."), t("Crea el esquema de una guía con título, resumen, cuatro secciones, enlaces y una acción posterior honesta.", "Crie o esquema de um guia com título, resumo, quatro seções, links e uma ação posterior honesta.", "Create an outline for a guide with title, summary, four sections, links, and an honest next action.")),
      lesson("search-console", t("Search Console: de señal a hipótesis", "Search Console: do sinal à hipótese", "Search Console: from signal to hypothesis"), t("Convierte impresiones, clics, posición y cobertura en una pregunta de aprendizaje, no en una conclusión automática.", "Converta impressões, cliques, posição e cobertura em uma pergunta de aprendizado, não em uma conclusão automática.", "Turn impressions, clicks, position, and coverage into a learning question, not an automatic conclusion."), [t("Rendimiento por consulta y página", "Desempenho por consulta e página", "Query and page performance"), t("Inspección, cobertura y sitemaps", "Inspeção, cobertura e sitemaps", "Inspection, coverage, and sitemaps"), t("Cambio, espera y verificación", "Mudança, espera e verificação", "Change, wait, and verification")], t("Prometer que una optimización causará una posición o volumen concreto.", "Prometer que uma otimização causará uma posição ou volume específico.", "Promising an optimization will cause a specific rank or volume."), t("A partir de un caso de muchas impresiones y pocos clics, separa tres hipótesis: promesa, intención y presentación.", "A partir de um caso de muitas impressões e poucos cliques, separe três hipóteses: promessa, intenção e apresentação.", "From a high-impression, low-click case, separate three hypotheses: promise, intent, and presentation."), t("Escribe una nota de priorización con señal, explicación posible, cambio reversible y fecha de revisión.", "Escreva uma nota de priorização com sinal, explicação possível, mudança reversível e data de revisão.", "Write a prioritization note with signal, possible explanation, reversible change, and review date."))
    ],
    portfolioBrief: t("Diseña una estrategia de descubrimiento para una colección de recursos sobre bienestar digital. Debe incluir mapa de intención, arquitectura, dos esquemas de página, plan de Search Console y riesgos de accesibilidad.", "Desenhe uma estratégia de descoberta para uma coleção de recursos sobre bem-estar digital. Deve incluir mapa de intenção, arquitetura, dois esquemas de página, plano de Search Console e riscos de acessibilidade.", "Design a discovery strategy for a collection of digital-wellbeing resources. Include an intent map, architecture, two page outlines, a Search Console plan, and accessibility risks."),
    deliverable: t("Mapa de intención, arquitectura, dos páginas modelo, registro de hipótesis y plan de medición.", "Mapa de intenção, arquitetura, duas páginas modelo, registro de hipóteses e plano de medição.", "Intent map, architecture, two model pages, hypothesis log, and measurement plan."),
    rubric: [{ criterion: t("Necesidad", "Necessidade", "Need"), evidence: t("La consulta se conecta con una tarea y una duda específicas.", "A consulta se conecta a uma tarefa e uma dúvida específicas.", "The query connects to a specific task and doubt.") }, { criterion: t("Estructura", "Estrutura", "Structure"), evidence: t("Las rutas y enlaces permiten explorar sin duplicar propósito.", "Rotas e links permitem explorar sem duplicar propósito.", "Paths and links enable exploration without duplicating purpose.") }, { criterion: t("Integridad", "Integridade", "Integrity"), evidence: t("El plan declara incertidumbre, accesibilidad y límites de medición.", "O plano declara incerteza, acessibilidade e limites de medição.", "The plan states uncertainty, accessibility, and measurement limits.") }],
    resourceIds: ["search-starter", "search-console-training", "web-vitals", "semrush-academy", "hubspot-content", "nngroup-ux-basics", "nngroup-research"]
  },
  {
    id: "marketing-conversion", order: 2, label: t("Marketing responsable", "Marketing responsável", "Responsible marketing"), title: t("De propuesta de valor a experimento de crecimiento", "Da proposta de valor ao experimento de crescimento", "From value proposition to growth experiment"),
    overview: t("Diseña campañas y experiencias posteriores al clic que sean claras, medibles y respetuosas de la autonomía de las personas.", "Desenhe campanhas e experiências pós-clique que sejam claras, mensuráveis e respeitosas da autonomia das pessoas.", "Design campaigns and post-click experiences that are clear, measurable, and respectful of people's autonomy."),
    outcomes: [t("Escribir una oferta que se pueda verificar", "Escrever uma oferta que possa ser verificada", "Write an offer that can be verified"), t("Conectar audiencia, creatividad y landing page", "Conectar audiência, criativo e landing page", "Connect audience, creative, and landing page"), t("Diseñar una medición que informe una decisión", "Desenhar uma medição que informe uma decisão", "Design measurement that informs a decision")],
    lessons: [
      lesson("positioning", t("Posicionamiento sin humo", "Posicionamento sem fumaça", "Positioning without hype"), t("Formula una promesa precisa, una alternativa y una razón para creer sin confundir persuasión con presión.", "Formule uma promessa precisa, uma alternativa e uma razão para acreditar sem confundir persuasão com pressão.", "Frame a precise promise, alternative, and reason to believe without confusing persuasion with pressure."), [t("Audiencia situacional", "Audiência situacional", "Situational audience"), t("Problema y resultado", "Problema e resultado", "Problem and outcome"), t("Diferenciador demostrable", "Diferenciador demonstrável", "Demonstrable differentiator")], t("Usar superlativos y urgencia artificial como sustituto de una propuesta clara.", "Usar superlativos e urgência artificial como substituto de uma proposta clara.", "Using superlatives and artificial urgency instead of a clear proposition."), t("Completa un lienzo de propuesta de valor para una herramienta de investigación que compite con hojas de cálculo.", "Complete um canvas de proposta de valor para uma ferramenta de pesquisa que compete com planilhas.", "Complete a value-proposition canvas for a research tool competing with spreadsheets."), t("Redacta tres versiones de una promesa: exploración, comparación y activación.", "Escreva três versões de uma promessa: exploração, comparação e ativação.", "Write three versions of a promise: discovery, comparison, and activation.")),
      lesson("campaign", t("Campaña como sistema de expectativas", "Campanha como sistema de expectativas", "Campaign as an expectation system"), t("Diseña la relación entre objetivo, audiencia, mensaje, creativo, página y siguiente decisión.", "Desenhe a relação entre objetivo, público, mensagem, criativo, página e próxima decisão.", "Design the relationship among objective, audience, message, creative, page, and next decision."), [t("Hipótesis de campaña", "Hipótese de campanha", "Campaign hypothesis"), t("Congruencia anuncio-página", "Coerência anúncio-página", "Ad-to-page congruence"), t("Fricción útil y decisión informada", "Fricção útil e decisão informada", "Useful friction and informed decision")], t("Optimizar el anuncio sin revisar si la landing cumple la expectativa creada.", "Otimizar o anúncio sem revisar se a landing cumpre a expectativa criada.", "Optimizing the ad without checking whether the landing fulfills the created expectation."), t("Audita un anuncio y landing ficticios con una tabla de expectativas, evidencia y ruptura.", "Audite um anúncio e landing fictícios com uma tabela de expectativas, evidência e ruptura.", "Audit a fictional ad and landing with an expectations, evidence, and break table."), t("Crea un flujo de campaña para un curso gratuito, incluyendo una salida para quien no es la audiencia.", "Crie um fluxo de campanha para um curso gratuito, incluindo uma saída para quem não é o público.", "Create a campaign flow for a free course, including an exit for people who are not the audience.")),
      lesson("measurement", t("Medir para aprender", "Medir para aprender", "Measure to learn"), t("Conecta una decisión de producto con eventos, señales cualitativas y un umbral de revisión.", "Conecte uma decisão de produto a eventos, sinais qualitativos e um limite de revisão.", "Connect a product decision with events, qualitative signals, and a review threshold."), [t("Métrica de resultado y diagnóstico", "Métrica de resultado e diagnóstico", "Outcome and diagnostic metric"), t("Evento, propiedad y privacidad", "Evento, propriedade e privacidade", "Event, property, and privacy"), t("Contrafactual y sesgo", "Contrafactual e viés", "Counterfactual and bias")], t("Celebrar una tasa sin preguntar qué decisión cambió ni qué daño pudo ocultar.", "Celebrar uma taxa sem perguntar qual decisão mudou ou que dano ela pode ter ocultado.", "Celebrating a rate without asking what decision changed or what harm it might hide."), t("Convierte el objetivo 'más conversiones' en una decisión, dos señales y una entrevista de seguimiento.", "Converta o objetivo 'mais conversões' em uma decisão, dois sinais e uma entrevista de acompanhamento.", "Turn the objective 'more conversions' into a decision, two signals, and a follow-up interview."), t("Diseña un diccionario de eventos para una campaña sin recopilar identificadores ni texto libre.", "Desenhe um dicionário de eventos para uma campanha sem coletar identificadores nem texto livre.", "Design an event dictionary for a campaign without collecting identifiers or free text.")),
      lesson("experiments", t("Experimentos con cuidado", "Experimentos com cuidado", "Experiments with care"), t("Define una hipótesis, variante, protección, criterio de parada y aprendizaje siguiente antes de experimentar.", "Defina uma hipótese, variante, proteção, critério de parada e próximo aprendizado antes de experimentar.", "Define a hypothesis, variant, protection, stop criterion, and next learning before experimenting."), [t("Cambio reversible", "Mudança reversível", "Reversible change"), t("Criterio de parada", "Critério de parada", "Stop criterion"), t("Aprendizaje transferible", "Aprendizado transferível", "Transferable learning")], t("Cambiar demasiadas cosas a la vez y atribuir el resultado a la idea preferida.", "Mudar muitas coisas ao mesmo tempo e atribuir o resultado à ideia preferida.", "Changing too many things at once and attributing the result to the favorite idea."), t("Convierte una afirmación de marketing en un experimento de una sola variable con una protección de confianza.", "Converta uma afirmação de marketing em um experimento de uma única variável com uma proteção de confiança.", "Turn a marketing claim into a single-variable experiment with a trust safeguard."), t("Escribe una retrospectiva que conserve resultado, incertidumbre, decisión y siguiente prueba.", "Escreva uma retrospectiva que preserve resultado, incerteza, decisão e próximo teste.", "Write a retrospective preserving result, uncertainty, decision, and next test."))
    ],
    portfolioBrief: t("Lanza en papel una campaña de adquisición ética para un programa de aprendizaje. Conecta promesa, creatividades, landing, analítica, experimento y plan de atención posterior.", "Lance no papel uma campanha de aquisição ética para um programa de aprendizagem. Conecte promessa, criativos, landing, analytics, experimento e plano de atenção posterior.", "Launch an ethical acquisition campaign on paper for a learning program. Connect promise, creative, landing, analytics, experiment, and post-launch care plan."),
    deliverable: t("Lienzo de posicionamiento, sistema anuncio-landing, plan de eventos, experimento y retrospectiva.", "Canvas de posicionamento, sistema anúncio-landing, plano de eventos, experimento e retrospectiva.", "Positioning canvas, ad-to-landing system, event plan, experiment, and retrospective."),
    rubric: [{ criterion: t("Claridad", "Clareza", "Clarity"), evidence: t("La oferta y el alcance se pueden comprobar.", "A oferta e o escopo podem ser verificados.", "The offer and scope can be verified.") }, { criterion: t("Congruencia", "Coerência", "Congruence"), evidence: t("Mensaje, experiencia y medición persiguen la misma hipótesis.", "Mensagem, experiência e medição perseguem a mesma hipótese.", "Message, experience, and measurement pursue the same hypothesis.") }, { criterion: t("Ética", "Ética", "Ethics"), evidence: t("El plan evita presión, segmentación dañina y tratamiento opaco de datos.", "O plano evita pressão, segmentação prejudicial e tratamento opaco de dados.", "The plan avoids pressure, harmful targeting, and opaque data handling.") }],
    resourceIds: ["skillshop", "marketing-platform", "google-ads", "analytics-dev", "hubspot-content", "figma-channel", "figma-beginners", "vaexperience"]
  },
  {
    id: "video-brand-distribution", order: 3, label: t("Marca y audiovisual", "Marca e audiovisual", "Brand and audiovisual"), title: t("De idea editorial a distribución con comunidad", "Da ideia editorial à distribuição com comunidade", "From editorial idea to distribution with community"),
    overview: t("Crea un sistema de vídeo y contenido que respeta la atención, facilita el acceso y aprende de la audiencia sin perseguir vanidad.", "Crie um sistema de vídeo e conteúdo que respeite a atenção, facilite o acesso e aprenda com o público sem perseguir vaidade.", "Create a video and content system that respects attention, enables access, and learns from the audience without chasing vanity."),
    outcomes: [t("Definir una tesis editorial reconocible", "Definir uma tese editorial reconhecível", "Define a recognizable editorial thesis"), t("Planificar una pieza audiovisual accesible", "Planejar uma peça audiovisual acessível", "Plan an accessible audiovisual piece"), t("Crear una retrospectiva de distribución", "Criar uma retrospectiva de distribuição", "Create a distribution retrospective")],
    lessons: [
      lesson("editorial-system", t("Tesis, audiencia y formato", "Tese, público e formato", "Thesis, audience, and format"), t("Construye una serie que parte de una pregunta útil y no de la necesidad de publicar sin criterio.", "Construa uma série que parte de uma pergunta útil e não da necessidade de publicar sem critério.", "Build a series that starts from a useful question, not a need to publish without judgment."), [t("Tesis editorial", "Tese editorial", "Editorial thesis"), t("Pilares y formatos", "Pilares e formatos", "Pillars and formats"), t("Valor antes que frecuencia", "Valor antes de frequência", "Value before frequency")], t("Copiar tendencias o formatos sin una razón para que la audiencia vuelva.", "Copiar tendências ou formatos sem uma razão para que o público volte.", "Copying trends or formats without a reason for the audience to return."), t("Define una tesis, tres pilares y dos formatos para una comunidad de diseñadores principiantes.", "Defina uma tese, três pilares e dois formatos para uma comunidade de designers iniciantes.", "Define a thesis, three pillars, and two formats for a beginner designer community."), t("Crea una matriz que relacione pregunta de audiencia, formato, resultado y señal de utilidad.", "Crie uma matriz que relacione pergunta do público, formato, resultado e sinal de utilidade.", "Create a matrix connecting audience question, format, outcome, and usefulness signal.")),
      lesson("production", t("Producción que incluye", "Produção que inclui", "Production that includes"), t("Integra guion, lenguaje claro, subtítulos, descripción y derechos desde la preproducción.", "Integre roteiro, linguagem clara, legendas, descrição e direitos desde a pré-produção.", "Integrate script, clear language, captions, description, and rights from pre-production."), [t("Guion por bloques", "Roteiro por blocos", "Block-based scripting"), t("Subtítulos y transcripción", "Legendas e transcrição", "Captions and transcript"), t("Créditos, licencias y consentimiento", "Créditos, licenças e consentimento", "Credits, licenses, and consent")], t("Tratar subtítulos o derechos como una tarea posterior a la publicación.", "Tratar legendas ou direitos como uma tarefa posterior à publicação.", "Treating captions or rights as a task after publishing."), t("Reescribe un guion de 90 segundos para incluir promesa, pasos, pausa cognitiva y cierre.", "Reescreva um roteiro de 90 segundos para incluir promessa, etapas, pausa cognitiva e encerramento.", "Rewrite a 90-second script to include promise, steps, a cognitive pause, and close."), t("Produce una hoja de rodaje que enumere derechos, accesibilidad y revisión de exactitud.", "Produza uma folha de gravação que enumere direitos, acessibilidade e revisão de precisão.", "Produce a shoot sheet listing rights, accessibility, and accuracy review.")),
      lesson("distribution", t("Distribución sin ruido", "Distribuição sem ruído", "Distribution without noise"), t("Diseña una distribución que adapta contexto y conserva la promesa central de la pieza.", "Desenhe uma distribuição que adapta o contexto e preserva a promessa central da peça.", "Design distribution that adapts context while preserving the piece's central promise."), [t("Pieza base y derivados", "Peça-base e derivados", "Anchor piece and derivatives"), t("Contexto de canal", "Contexto de canal", "Channel context"), t("Enlaces de continuidad", "Links de continuidade", "Continuity links")], t("Publicar el mismo recorte en todos los canales sin considerar intención, formato o permiso.", "Publicar o mesmo recorte em todos os canais sem considerar intenção, formato ou permissão.", "Publishing the same clip across every channel without considering intent, format, or permission."), t("Transforma un vídeo largo en una ruta de distribución que preserve contexto y accesibilidad.", "Transforme um vídeo longo em uma rota de distribuição que preserve contexto e acessibilidade.", "Turn a long video into a distribution path that preserves context and accessibility."), t("Crea un calendario de cuatro semanas con propósito, audiencia, CTA y evidencia de cada publicación.", "Crie um calendário de quatro semanas com propósito, público, CTA e evidência de cada publicação.", "Create a four-week calendar with purpose, audience, CTA, and evidence for each post.")),
      lesson("community", t("Escuchar y aprender de la comunidad", "Ouvir e aprender com a comunidade", "Listen and learn from community"), t("Convierte comentarios, retención y preguntas en un ciclo de aprendizaje editorial.", "Converta comentários, retenção e perguntas em um ciclo de aprendizado editorial.", "Turn comments, retention, and questions into an editorial learning cycle."), [t("Señal de satisfacción", "Sinal de satisfação", "Satisfaction signal"), t("Moderación y límites", "Moderação e limites", "Moderation and boundaries"), t("Retro de contenido", "Retro de conteúdo", "Content retro")], t("Usar vistas aisladas como prueba de valor, comprensión o confianza.", "Usar visualizações isoladas como prova de valor, compreensão ou confiança.", "Using isolated views as proof of value, understanding, or trust."), t("Clasifica 15 comentarios ficticios por intención: pregunta, barrera, corrección, historia o spam.", "Classifique 15 comentários fictícios por intenção: pergunta, barreira, correção, história ou spam.", "Classify 15 fictitious comments by intent: question, barrier, correction, story, or spam."), t("Escribe una retro mensual que combine señales, lectura humana, decisión y cuidado de comunidad.", "Escreva uma retrospectiva mensal que combine sinais, leitura humana, decisão e cuidado com a comunidade.", "Write a monthly retro combining signals, human reading, decision, and community care."))
    ],
    portfolioBrief: t("Diseña una serie audiovisual de seis semanas para hacer accesible una habilidad de UX. Debe conectar tesis, guiones, plan de accesibilidad, distribución, moderación y revisión.", "Desenhe uma série audiovisual de seis semanas para tornar acessível uma habilidade de UX. Deve conectar tese, roteiros, plano de acessibilidade, distribuição, moderação e revisão.", "Design a six-week audiovisual series that makes a UX skill accessible. Connect thesis, scripts, accessibility plan, distribution, moderation, and review."),
    deliverable: t("Sistema editorial, dos guiones, checklist de producción, calendario de distribución y retrospectiva.", "Sistema editorial, dois roteiros, checklist de produção, calendário de distribuição e retrospectiva.", "Editorial system, two scripts, production checklist, distribution calendar, and retrospective."),
    rubric: [{ criterion: t("Relevancia", "Relevância", "Relevance"), evidence: t("La serie responde a preguntas concretas de una audiencia definida.", "A série responde a perguntas concretas de um público definido.", "The series answers concrete questions for a defined audience.") }, { criterion: t("Acceso", "Acesso", "Access"), evidence: t("Subtítulos, transcripción, derechos y lenguaje se planifican desde el inicio.", "Legendas, transcrição, direitos e linguagem são planejados desde o início.", "Captions, transcript, rights, and language are planned from the start.") }, { criterion: t("Aprendizaje", "Aprendizado", "Learning"), evidence: t("La distribución incluye una forma de escuchar y adaptar el siguiente ciclo.", "A distribuição inclui uma forma de ouvir e adaptar o próximo ciclo.", "Distribution includes a way to listen and adapt the next cycle.") }],
    resourceIds: ["youtube-creators", "google-creators", "w3c-perspectives", "google-search-central-channel", "nngroup-channel", "figma-channel", "caler-edwards", "ux-salon"]
  },
  {
    id: "research-ops-ai", order: 4, label: t("Research Ops e IA", "Research Ops e IA", "Research Ops and AI"), title: t("Investigación conectada: Workspace, IA y trazabilidad", "Pesquisa conectada: Workspace, IA e rastreabilidade", "Connected research: Workspace, AI, and traceability"),
    overview: t("Convierte la investigación en un sistema respetuoso de colaboración, evidencia, automatización proporcional e IA supervisada.", "Transforme a pesquisa em um sistema respeitoso de colaboração, evidência, automação proporcional e IA supervisionada.", "Turn research into a respectful system of collaboration, evidence, proportional automation, and supervised AI."),
    outcomes: [t("Diseñar un repositorio de evidencia recuperable", "Desenhar um repositório de evidências recuperável", "Design a recoverable evidence repository"), t("Automatizar tareas sin opacar decisiones", "Automatizar tarefas sem ocultar decisões", "Automate tasks without obscuring decisions"), t("Usar IA con evaluación y salida humana", "Usar IA com avaliação e saída humana", "Use AI with evaluation and human handoff")],
    lessons: [
      lesson("research-repository", t("Evidencia que se puede seguir", "Evidência rastreável", "Traceable evidence"), t("Diseña un espacio colaborativo que conecta consentimiento, fuente, hallazgo, decisión y acceso.", "Desenhe um espaço colaborativo que conecte consentimento, fonte, achado, decisão e acesso.", "Design a collaborative space connecting consent, source, finding, decision, and access."), [t("Estructura de Drive", "Estrutura do Drive", "Drive structure"), t("Nombres y versiones", "Nomes e versões", "Names and versions"), t("Matriz de evidencia", "Matriz de evidências", "Evidence matrix")], t("Mezclar notas, interpretaciones y decisiones sin conservar la fuente o el nivel de confianza.", "Misturar notas, interpretações e decisões sem preservar a fonte ou o nível de confiança.", "Mixing notes, interpretations, and decisions without preserving the source or confidence level."), t("Crea una estructura de Drive y Sheet para ocho entrevistas simuladas, con acceso y retención definidos.", "Crie uma estrutura de Drive e Sheet para oito entrevistas simuladas, com acesso e retenção definidos.", "Create a Drive and Sheet structure for eight simulated interviews with defined access and retention."), t("Diseña una matriz de evidencia que una observación, cita anonimizada, interpretación y decisión pendiente.", "Desenhe uma matriz de evidências que una observação, citação anonimizada, interpretação e decisão pendente.", "Design an evidence matrix joining observation, anonymized quote, interpretation, and pending decision.")),
      lesson("automation", t("Automatizar lo repetible", "Automatizar o repetível", "Automate the repeatable"), t("Diferencia una tarea administrativa de una decisión de investigación y conserva la intervención humana relevante.", "Diferencie uma tarefa administrativa de uma decisão de pesquisa e preserve a intervenção humana relevante.", "Distinguish an administrative task from a research decision and preserve relevant human intervention."), [t("Entrada, transformación y salida", "Entrada, transformação e saída", "Input, transformation, and output"), t("Permisos mínimos", "Permissões mínimas", "Minimum permissions"), t("Fallback y registro de errores", "Fallback e registro de erros", "Fallback and error log")], t("Automatizar la interpretación o priorización sin revisión porque parece ahorrar tiempo.", "Automatizar a interpretação ou priorização sem revisão porque parece economizar tempo.", "Automating interpretation or prioritization without review because it seems to save time."), t("Modela un flujo de Form a Sheet que asigne etiquetas iniciales y escale ambigüedades a revisión humana.", "Modele um fluxo de Form para Sheet que atribua rótulos iniciais e escale ambiguidades para revisão humana.", "Model a Form-to-Sheet flow that assigns initial labels and escalates ambiguity to human review."), t("Redacta un contrato de automatización con propietario, permisos, error, revisión y retirada.", "Redija um contrato de automação com responsável, permissões, erro, revisão e retirada.", "Draft an automation contract with owner, permissions, error, review, and retirement.")),
      lesson("ai-synthesis", t("IA para asistir, no para afirmar", "IA para assistir, não para afirmar", "AI to assist, not assert"), t("Diseña una asistencia de IA que declara alcance, datos permitidos, evaluación, incertidumbre y escalamiento.", "Desenhe uma assistência de IA que declare escopo, dados permitidos, avaliação, incerteza e escalonamento.", "Design AI assistance that states scope, permitted data, evaluation, uncertainty, and escalation."), [t("Caso de uso defendible", "Caso de uso defensável", "Defensible use case"), t("Prompt estructurado", "Prompt estruturado", "Structured prompt"), t("Conjunto de evaluación", "Conjunto de avaliação", "Evaluation set")], t("Pegar información sensible o tratar un resumen generado como hallazgo validado.", "Colar informação sensível ou tratar um resumo gerado como achado validado.", "Pasting sensitive information or treating a generated summary as a validated finding."), t("Convierte una tarea de síntesis en un contrato con entradas simuladas, salida esperada, fallos y revisión humana.", "Converta uma tarefa de síntese em um contrato com entradas simuladas, saída esperada, falhas e revisão humana.", "Turn a synthesis task into a contract with simulated inputs, expected output, failures, and human review."), t("Crea una rúbrica para comparar tres resultados de IA sin usar datos reales de participantes.", "Crie uma rubrica para comparar três resultados de IA sem usar dados reais de participantes.", "Create a rubric to compare three AI outputs without using real participant data.")),
      lesson("decision-ops", t("De evidencia a decisión compartida", "Da evidência à decisão compartilhada", "From evidence to shared decision"), t("Presenta hallazgos con contexto, confianza, decisión propuesta, disenso y fecha de revisión.", "Apresente achados com contexto, confiança, decisão proposta, discordância e data de revisão.", "Present findings with context, confidence, proposed decision, dissent, and review date."), [t("Log de decisiones", "Log de decisões", "Decision log"), t("Supuesto y disenso", "Suposição e discordância", "Assumption and dissent"), t("Revisión posterior", "Revisão posterior", "Post-review")], t("Presentar un insight como certeza y ocultar los límites del método o los contraejemplos.", "Apresentar um insight como certeza e ocultar os limites do método ou contraexemplos.", "Presenting an insight as certainty and hiding method limits or counterexamples."), t("Convierte tres observaciones en un documento de decisión que mantenga evidencia, incertidumbre y alternativa.", "Converta três observações em um documento de decisão que preserve evidência, incerteza e alternativa.", "Turn three observations into a decision document retaining evidence, uncertainty, and alternative."), t("Diseña una revisión mensual de Research Ops que mida recuperación, calidad y riesgos de privacidad.", "Desenhe uma revisão mensal de Research Ops que meça recuperação, qualidade e riscos de privacidade.", "Design a monthly Research Ops review that measures retrieval, quality, and privacy risks."))
    ],
    portfolioBrief: t("Construye el plano operativo de investigación de un equipo de producto: repositorio, flujo de recepción, automatización limitada, protocolo de IA, matriz de evidencia y log de decisiones.", "Construa o plano operacional de pesquisa de uma equipe de produto: repositório, fluxo de recepção, automação limitada, protocolo de IA, matriz de evidências e log de decisões.", "Build the research operations blueprint for a product team: repository, intake flow, limited automation, AI protocol, evidence matrix, and decision log."),
    deliverable: t("Mapa de repositorio, contrato de automatización, protocolo de IA, matriz de evidencia y agenda de revisión.", "Mapa de repositório, contrato de automação, protocolo de IA, matriz de evidências e agenda de revisão.", "Repository map, automation contract, AI protocol, evidence matrix, and review agenda."),
    rubric: [{ criterion: t("Trazabilidad", "Rastreabilidade", "Traceability"), evidence: t("Cada hallazgo conserva fuente, contexto y nivel de confianza.", "Cada achado preserva fonte, contexto e nível de confiança.", "Every finding keeps its source, context, and confidence level.") }, { criterion: t("Proporcionalidad", "Proporcionalidade", "Proportionality"), evidence: t("La automatización y la IA se limitan a tareas adecuadas y revisables.", "A automação e a IA são limitadas a tarefas adequadas e revisáveis.", "Automation and AI are limited to appropriate, reviewable tasks.") }, { criterion: t("Gobernanza", "Governança", "Governance"), evidence: t("Permisos, responsable, fallo y revisión están definidos.", "Permissões, responsável, falha e revisão estão definidos.", "Permissions, owner, failure, and review are defined.") }],
    resourceIds: ["workspace-learning", "workspace-developers", "apps-script", "google-ai-dev", "responsible-ai", "developer-pathways", "google-codelabs", "nngroup-ai-design", "w3c-wai-channel", "nngroup-research", "femke-design"]
  }
];

export const videoLibrary: VideoResource[] = [
  { id: "search-starter", title: "SEO Starter Guide", publisher: "Google Search Central", url: "https://developers.google.com/search/docs/fundamentals/seo-starter-guide", format: "documentation", level: "foundation", topics: ["seo", "content"], language: "en", access: "open-documentation", note: t("Guía fundamental sobre contenido útil, rastreo, indexación, títulos, enlaces y sitemaps.", "Guia fundamental sobre conteúdo útil, rastreamento, indexação, títulos, links e sitemaps.", "Foundational guide on helpful content, crawling, indexing, titles, links, and sitemaps."), why: t("Usa sus límites para evitar promesas de ranking y técnicas manipulativas.", "Use seus limites para evitar promessas de ranking e técnicas manipuladoras.", "Use its boundaries to avoid ranking promises and manipulative techniques.") },
  { id: "search-console-training", title: "Search Console Training", publisher: "Google Search Central", url: "https://www.youtube.com/playlist?list=PLKoqnv2vTMUOnQn-lNDfT38X9gA_CHxTo", format: "playlist", level: "foundation", topics: ["seo", "analytics", "video"], language: "en", access: "public-link", note: t("Serie oficial de vídeos sobre verificación, informes de rendimiento e inspección de URL.", "Série oficial de vídeos sobre verificação, relatórios de desempenho e inspeção de URL.", "Official video series on verification, performance reports, and URL inspection."), why: t("Inclúyela como práctica de diagnóstico, no como garantía de tráfico.", "Inclua-a como prática de diagnóstico, não como garantia de tráfego.", "Include it as diagnostic practice, not as a traffic guarantee.") },
  { id: "web-vitals", title: "Core Web Vitals", publisher: "Google Search Central / web.dev", url: "https://developers.google.com/search/docs/appearance/core-web-vitals", format: "documentation", level: "intermediate", topics: ["seo", "ux", "performance"], language: "en", access: "open-documentation", note: t("Referencia de LCP, INP y CLS con vínculos a medición y depuración.", "Referência de LCP, INP e CLS com links para medição e depuração.", "Reference for LCP, INP, and CLS with links to measurement and debugging."), why: t("Conecta rendimiento técnico con experiencia, no con una fórmula de posicionamiento.", "Conecta desempenho técnico com experiência, não com uma fórmula de posicionamento.", "Connects technical performance with experience, not a ranking formula.") },
  { id: "skillshop", title: "Google Skillshop", publisher: "Google", url: "https://skillshop.withgoogle.com/", format: "course", level: "foundation", topics: ["marketing", "ads", "analytics"], language: "multilingual", access: "public-link", note: t("Cursos de Ads, Marketing Platform, Analytics, Business Profile, Ad Manager y AdMob.", "Cursos de Ads, Marketing Platform, Analytics, Business Profile, Ad Manager e AdMob.", "Courses for Ads, Marketing Platform, Analytics, Business Profile, Ad Manager, and AdMob."), why: t("Sus certificaciones son externas; UX Academy solo enlaza la formación.", "Suas certificações são externas; UX Academy apenas vincula a formação.", "Its certifications are external; UX Academy only links to the training.") },
  { id: "marketing-platform", title: "Google Marketing Platform", publisher: "Google", url: "https://www.youtube.com/c/googlemarketingplatform", format: "channel", level: "intermediate", topics: ["marketing", "analytics", "video"], language: "en", access: "public-link", note: t("Canal público sobre planificación, compra, medición y optimización de medios digitales.", "Canal público sobre planejamento, compra, medição e otimização de mídia digital.", "Public channel on planning, buying, measuring, and optimizing digital media."), why: t("Sirve para discutir medición y operación; no se re-publican sus piezas.", "Serve para discutir medição e operação; seus materiais não são republicados.", "Supports discussion of measurement and operation; its pieces are not republished.") },
  { id: "google-ads", title: "Google Ads", publisher: "Google", url: "https://business.google.com/us/google-ads/", format: "documentation", level: "foundation", topics: ["marketing", "ads"], language: "multilingual", access: "public-link", note: t("Punto de entrada oficial para campañas de búsqueda y vídeo, con referencia a formación.", "Ponto de entrada oficial para campanhas de busca e vídeo, com referência a treinamento.", "Official entry point for Search and video campaigns, with training references."), why: t("La práctica académica evita lanzamientos, gastos y audiencias reales.", "A prática acadêmica evita lançamentos, gastos e públicos reais.", "Academic practice avoids launches, spend, and real audiences.") },
  { id: "analytics-dev", title: "Google Analytics for Developers", publisher: "Google", url: "https://developers.google.com/analytics", format: "documentation", level: "intermediate", topics: ["marketing", "analytics", "privacy"], language: "en", access: "open-documentation", note: t("Rutas de analítica para personas que empiezan, profesionales de marketing y desarrolladores.", "Trilhas de analytics para iniciantes, profissionais de marketing e desenvolvedores.", "Analytics paths for beginners, marketing professionals, and developers."), why: t("Apoya planes de eventos con datos mínimos y límites de interpretación.", "Apoia planos de eventos com dados mínimos e limites de interpretação.", "Supports event plans with minimum data and interpretation limits.") },
  { id: "youtube-creators", title: "YouTube Creators Resources", publisher: "YouTube", url: "https://www.youtube.com/creators/resources/", format: "channel", level: "foundation", topics: ["video", "brand", "marketing"], language: "multilingual", access: "public-link", note: t("Recursos de creación, políticas, ayuda y actualizaciones para personas creadoras.", "Recursos de criação, políticas, ajuda e atualizações para criadores.", "Creation resources, policies, help, and updates for creators."), why: t("Enmarca producción, acceso y política antes que tácticas de vanidad.", "Enquadra produção, acesso e política antes de táticas de vaidade.", "Frames production, access, and policy before vanity tactics.") },
  { id: "google-creators", title: "Google for Creators", publisher: "Google", url: "https://creators.google/", format: "course", level: "foundation", topics: ["video", "brand", "content"], language: "en", access: "public-link", note: t("Guías de marca, audiencia y creación conectadas con productos de Google.", "Guias de marca, público e criação conectados a produtos do Google.", "Brand, audience, and creation guides connected to Google products."), why: t("Se usa como referencia de distribución responsable y construcción de comunidad.", "É usado como referência de distribuição responsável e construção de comunidade.", "Used as a reference for responsible distribution and community building.") },
  { id: "google-search-central-channel", title: "Google Search Central", publisher: "Google", url: "https://www.youtube.com/@GoogleSearchCentral", format: "channel", level: "intermediate", topics: ["seo", "video"], language: "en", access: "public-link", note: t("Canal oficial para entender y mejorar la presencia de un sitio en Google Search.", "Canal oficial para entender e melhorar a presença de um site no Google Search.", "Official channel to understand and improve a site's presence in Google Search."), why: t("Selecciona playlists por necesidad, no videos aislados por tendencia.", "Selecione playlists por necessidade, não vídeos isolados por tendência.", "Select playlists by need, not isolated trending videos.") },
  { id: "nngroup-channel", title: "NN/g", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/channel/UC2oCugzU6W8-h95W7eBTUEg", format: "channel", level: "intermediate", topics: ["ux", "research", "accessibility"], language: "en", access: "public-link", note: t("Canal de expertos de UX sobre investigación, estrategia, accesibilidad y diseño.", "Canal de especialistas em UX sobre pesquisa, estratégia, acessibilidade e design.", "UX expert channel covering research, strategy, accessibility, and design."), why: t("Complementa las prácticas originales de investigación y evaluación.", "Complementa as práticas originais de pesquisa e avaliação.", "Complements original research and evaluation practice.") },
  { id: "w3c-perspectives", title: "Web Accessibility Perspectives", publisher: "W3C WAI", url: "https://www.w3.org/WAI/perspective-videos/", format: "playlist", level: "foundation", topics: ["ux", "accessibility", "video"], language: "multilingual", access: "public-link", note: t("Colección de diez vídeos breves sobre barreras y beneficios de accesibilidad, con subtítulos y transcripciones.", "Coleção de dez vídeos curtos sobre barreiras e benefícios de acessibilidade, com legendas e transcrições.", "Collection of ten short videos on accessibility barriers and benefits, with captions and transcripts."), why: t("Aporta perspectivas humanas antes de convertir accesibilidad en un checklist.", "Traz perspectivas humanas antes de transformar acessibilidade em checklist.", "Brings human perspectives before turning accessibility into a checklist.") },
  { id: "workspace-learning", title: "Google Workspace Learning Center", publisher: "Google", url: "https://workspace.google.com/training/", format: "course", level: "foundation", topics: ["workspace", "research", "collaboration"], language: "multilingual", access: "public-link", note: t("Guías, inicio rápido y recursos por producto para correo, documentos, archivos, calendarios y reuniones.", "Guias, início rápido e recursos por produto para e-mail, documentos, arquivos, calendários e reuniões.", "Guides, quick starts, and product resources for mail, docs, files, calendars, and meetings."), why: t("Soporta un sistema de investigación colaborativo sin modificar cuentas reales.", "Apoia um sistema de pesquisa colaborativo sem modificar contas reais.", "Supports a collaborative research system without modifying real accounts.") },
  { id: "workspace-developers", title: "Google Workspace Developers", publisher: "Google", url: "https://www.youtube.com/channel/UCUcg6az6etU_gRtZVAhBXaw", format: "channel", level: "intermediate", topics: ["workspace", "automation", "video"], language: "en", access: "public-link", note: t("Canal público para construir soluciones e integraciones con Google Workspace.", "Canal público para construir soluções e integrações com o Google Workspace.", "Public channel for building Google Workspace solutions and integrations."), why: t("Complementa los límites de automatización y permisos del itinerario.", "Complementa os limites de automação e permissões da trilha.", "Complements the pathway's automation and permission boundaries.") },
  { id: "apps-script", title: "Google Apps Script", publisher: "Google", url: "https://developers.google.com/apps-script", format: "documentation", level: "intermediate", topics: ["workspace", "automation", "ai"], language: "en", access: "open-documentation", note: t("Documentación, muestras y guías para automatizar y extender Workspace.", "Documentação, exemplos e guias para automatizar e estender o Workspace.", "Documentation, samples, and guides to automate and extend Workspace."), why: t("El curso exige contrato de permisos, fallback y responsable antes de automatizar.", "O curso exige contrato de permissões, fallback e responsável antes de automatizar.", "The course requires a permission, fallback, and owner contract before automating.") },
  { id: "google-ai-dev", title: "Google AI for Developers", publisher: "Google", url: "https://ai.google.dev/", format: "documentation", level: "intermediate", topics: ["ai", "development", "responsibility"], language: "en", access: "open-documentation", note: t("Portal de modelos, Gemini API, AI Studio, Gemma, AI Edge y material de construcción responsable.", "Portal de modelos, Gemini API, AI Studio, Gemma, AI Edge e material de construção responsável.", "Portal for models, Gemini API, AI Studio, Gemma, AI Edge, and responsible building material."), why: t("Se usa para diseñar evaluaciones y límites, no para cargar información sensible.", "É usado para desenhar avaliações e limites, não para carregar informações sensíveis.", "Used to design evaluations and limits, not to upload sensitive information.") },
  { id: "responsible-ai", title: "Responsible GenAI Toolkit", publisher: "Google", url: "https://ai.google.dev/responsible/", format: "documentation", level: "advanced", topics: ["ai", "responsibility", "security"], language: "en", access: "open-documentation", note: t("Guías y herramientas para diseñar, construir y evaluar IA generativa de forma responsable.", "Guias e ferramentas para desenhar, construir e avaliar IA generativa de forma responsável.", "Guides and tools to design, build, and evaluate generative AI responsibly."), why: t("Informa las rúbricas de casos de uso, evaluación y escalamiento humano.", "Informa as rubricas de casos de uso, avaliação e escalonamento humano.", "Informs rubrics for use cases, evaluation, and human escalation.") },
  { id: "developer-pathways", title: "Google Developer Learning Pathways", publisher: "Google", url: "https://developers.google.com/learn/pathways", format: "course", level: "foundation", topics: ["development", "ai", "workspace"], language: "en", access: "public-link", note: t("Rutas secuenciales de artículos, codelabs, quizzes y vídeos por tecnología.", "Trilhas sequenciais de artigos, codelabs, quizzes e vídeos por tecnologia.", "Sequential paths of articles, codelabs, quizzes, and videos by technology."), why: t("Permite que cada estudiante profundice sin duplicar el itinerario original.", "Permite que cada estudante aprofunde sem duplicar a trilha original.", "Lets each learner go deeper without duplicating the original pathway.") },
  { id: "google-codelabs", title: "Google Codelabs", publisher: "Google", url: "https://codelabs.developers.google.com/", format: "course", level: "intermediate", topics: ["development", "ai", "workspace", "android"], language: "en", access: "public-link", note: t("Tutoriales prácticos de Android, Cloud, Firebase, Chrome, IA y más.", "Tutoriais práticos de Android, Cloud, Firebase, Chrome, IA e mais.", "Hands-on tutorials for Android, Cloud, Firebase, Chrome, AI, and more."), why: t("Se enlazan como práctica técnica opcional con condiciones de origen visibles.", "São vinculados como prática técnica opcional com condições de origem visíveis.", "Linked as optional technical practice with visible source conditions.") },
  { id: "semrush-academy", title: "Semrush Academy", publisher: "Semrush", url: "https://www.semrush.com/academy/", format: "course", level: "intermediate", topics: ["seo", "marketing", "content"], language: "multilingual", access: "public-link", note: t("Cursos y webinarios sobre SEO, contenido, analítica, IA y marketing digital.", "Cursos e webinars sobre SEO, conteúdo, analytics, IA e marketing digital.", "Courses and webinars on SEO, content, analytics, AI, and digital marketing."), why: t("Fuente comercial complementaria, no estándar oficial ni garantía de método.", "Fonte comercial complementar, não padrão oficial nem garantia de método.", "Commercial complementary source, not an official standard or a method guarantee.") },
    { id: "hubspot-content", title: "Content Marketing Certification Course", publisher: "HubSpot Academy", url: "https://academy.hubspot.com/courses/content-marketing", format: "course", level: "foundation", topics: ["marketing", "content", "brand"], language: "en", access: "public-link", note: t("Curso gratuito de marketing de contenidos y planificación editorial.", "Curso gratuito de marketing de conteúdo e planejamento editorial.", "Free course on content marketing and editorial planning."), why: t("Se curan conceptos y no se atribuye la certificación a UX Academy.", "Conceitos são curados e a certificação não é atribuída à UX Academy.", "Concepts are curated and certification is not attributed to UX Academy.") },
  { id: "nngroup-channel", title: "NNGroup UX Research & Design", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/channel/UC2oCugzU6W8-h95W7eBTUEg", format: "channel", level: "foundation", topics: ["ux", "research", "accessibility", "video"], language: "en", access: "public-link", note: t("Canal de referencia con investigación aplicada sobre UX, usabilidad, estrategia, accesibilidad y profesión.", "Canal de referência com pesquisa aplicada sobre UX, usabilidade, estratégia, acessibilidade e carreira.", "Reference channel with applied research on UX, usability, strategy, accessibility, and the profession."), why: t("Aporta contraste entre opinión y evidencia; abre siempre la fuente original.", "Traz contraste entre opinião e evidência; abra sempre a fonte original.", "Helps contrast opinion with evidence; always open the original source.") },
  { id: "nngroup-heuristics", title: "The 10 Usability Heuristics", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/playlist?list=PLJOFJ3Ok_idtb2YeifXlG1-TYoMBLoG6I", format: "playlist", level: "foundation", topics: ["ux", "usability", "video"], language: "en", access: "public-link", note: t("Playlist breve para relacionar heurísticas con problemas observables de interfaz.", "Playlist curta para relacionar heurísticas com problemas observáveis de interface.", "Short playlist for relating heuristics to observable interface problems."), why: t("Se usa como práctica de evaluación, nunca como sustituto de investigación con personas.", "É usada como prática de avaliação, nunca como substituto de pesquisa com pessoas.", "Use it for evaluation practice, never as a substitute for research with people.") },
  { id: "nngroup-research", title: "UX Research Methods & Usability Testing", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/playlist?list=PLJOFJ3Ok_idtiMTz8fAiF1ElcKJM7Rncj", format: "playlist", level: "intermediate", topics: ["ux", "research", "testing", "video"], language: "en", access: "public-link", note: t("Selección de métodos de investigación y pruebas de usabilidad para orientar preguntas y decisiones.", "Seleção de métodos de pesquisa e testes de usabilidade para orientar perguntas e decisões.", "Selection of research methods and usability testing to guide questions and decisions."), why: t("Ayuda a escoger métodos proporcionales y a declarar límites de evidencia.", "Ajuda a escolher métodos proporcionais e declarar limites da evidência.", "Helps choose proportional methods and state evidence limits.") },
  { id: "nngroup-ux-basics", title: "What is User Experience (UX)?", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/playlist?list=PLJOFJ3Ok_idvhv7_ezZd9F2mdfPk9JwPt", format: "playlist", level: "foundation", topics: ["ux", "foundations", "video"], language: "en", access: "public-link", note: t("Conceptos introductorios de UX, diseño centrado en personas y mapeo.", "Conceitos introdutórios de UX, design centrado em pessoas e mapeamento.", "Introductory concepts of UX, human-centered design, and mapping."), why: t("Sirve para fijar vocabulario común antes de pasar a la práctica.", "Serve para fixar um vocabulário comum antes da prática.", "Useful for establishing a shared vocabulary before practice.") },
  { id: "nngroup-ai-design", title: "Outcome-Oriented Design: The Era of AI Design", publisher: "Nielsen Norman Group", url: "https://www.youtube.com/watch?v=orvtAMGBgPE", format: "video", level: "advanced", topics: ["ux", "ai", "video"], language: "en", access: "public-link", note: t("Vídeo breve sobre orientar el diseño por resultados y no solo por producción de pantallas.", "Vídeo curto sobre orientar o design por resultados e não apenas pela produção de telas.", "Short video about orienting design around outcomes rather than screen production alone."), why: t("Conecta con la unidad de IA supervisada y criterio profesional.", "Conecta com a unidade de IA supervisionada e critério profissional.", "Connects with supervised AI and professional judgment.") },
  { id: "w3c-wai-channel", title: "W3C Web Accessibility Initiative", publisher: "W3C WAI", url: "https://www.youtube.com/channel/UCU6ljj3m1fglIPjSjs2DpRA", format: "channel", level: "foundation", topics: ["accessibility", "ux", "video"], language: "en", access: "public-link", note: t("Canal oficial de WAI con estándares, principios y perspectivas de accesibilidad web.", "Canal oficial da WAI com padrões, princípios e perspectivas de acessibilidade web.", "Official WAI channel with web accessibility standards, principles, and perspectives."), why: t("Aporta una fuente normativa y experiencias de uso que complementan el checklist.", "Traz uma fonte normativa e experiências de uso que complementam o checklist.", "Adds a standards source and user perspectives that complement a checklist.") },
  { id: "w3c-accessibility-compilation", title: "Web Accessibility Perspectives — Compilation", publisher: "W3C WAI", url: "https://www.youtube.com/watch?v=3f31oufqFSM", format: "video", level: "foundation", topics: ["accessibility", "ux", "video"], language: "en", access: "public-link", note: t("Compilación de diez perspectivas: teclado, contraste, texto a voz, reconocimiento de voz, subtítulos y más.", "Compilação de dez perspectivas: teclado, contraste, texto para fala, reconhecimento de fala, legendas e mais.", "Compilation of ten perspectives: keyboard, contrast, text to speech, speech recognition, captions, and more."), why: t("Se puede ver con alternativa de texto y se enlaza desde el editor original.", "Pode ser visto com alternativa textual e é vinculado à fonte original.", "Pair it with a text alternative and link to the original publisher.") },
  { id: "figma-channel", title: "Figma", publisher: "Figma", url: "https://www.youtube.com/@Figma", format: "channel", level: "foundation", topics: ["ux", "ui", "prototyping", "video"], language: "en", access: "public-link", note: t("Canal oficial con tutoriales de diseño, prototipado, sistemas y flujos de trabajo asistidos por IA.", "Canal oficial com tutoriais de design, prototipagem, sistemas e fluxos assistidos por IA.", "Official channel with tutorials on design, prototyping, systems, and AI-assisted workflows."), why: t("Se usa para aprender la herramienta sin convertirla en el objetivo del método.", "É usado para aprender a ferramenta sem transformá-la no objetivo do método.", "Use it to learn the tool without making the tool the method's goal.") },
  { id: "figma-beginners", title: "Figma Design for beginners", publisher: "Figma", url: "https://www.youtube.com/playlist?list=PLXDU_eVOJTx5IuSrbtanZHnDuPB3Hx0hq", format: "playlist", level: "foundation", topics: ["ui", "prototyping", "video"], language: "en", access: "public-link", note: t("Curso oficial de 18 lecciones para empezar con Figma Design.", "Curso oficial de 18 lições para começar com Figma Design.", "Official 18-lesson course for getting started with Figma Design."), why: t("Permite practicar componentes y prototipos después de entender el problema.", "Permite praticar componentes e protótipos depois de entender o problema.", "Enables component and prototype practice after understanding the problem.") },
  { id: "figma-auto-layout", title: "Auto layout in Figma", publisher: "Figma", url: "https://www.youtube.com/watch?v=PNJxeD29ZTg&list=PLXDU_eVOJTx55HFubfbTL3ellJjBM2QE2", format: "playlist", level: "intermediate", topics: ["ui", "design-systems", "video"], language: "en", access: "public-link", note: t("Playlist de auto layout para crear diseños flexibles y componentes mantenibles.", "Playlist de auto layout para criar designs flexíveis e componentes sustentáveis.", "Auto-layout playlist for creating flexible designs and maintainable components."), why: t("Conecta decisiones visuales con comportamiento responsive y consistencia.", "Conecta decisões visuais com comportamento responsive e consistência.", "Connects visual decisions with responsive behavior and consistency.") },
  { id: "femke-design", title: "Femke.design", publisher: "Femke van Schoonhoven", url: "https://www.youtube.com/c/femkedesign", format: "channel", level: "intermediate", topics: ["ux", "research", "career", "video"], language: "en", access: "public-link", note: t("Canal sobre UX, investigación, prototipado, carrera y aprendizaje desde la práctica de producto.", "Canal sobre UX, pesquisa, prototipagem, carreira e aprendizagem na prática de produto.", "Channel about UX, research, prototyping, career, and learning from product practice."), why: t("Ofrece una mirada profesional complementaria; el alumno debe contrastar opiniones con evidencia.", "Oferece uma visão profissional complementar; o aluno deve contrastar opiniões com evidências.", "Offers a complementary professional perspective; learners should contrast opinions with evidence.") },
  { id: "vaexperience", title: "VAexperience", publisher: "Vy Alechnavicius", url: "https://www.youtube.com/@vaexperience/videos", format: "channel", level: "intermediate", topics: ["ux", "portfolio", "career", "video"], language: "en", access: "public-link", note: t("Canal con revisiones de portfolio, curriculum y perspectivas de liderazgo de diseño.", "Canal com revisões de portfólio, currículo e perspectivas de liderança de design.", "Channel with portfolio reviews, resume guidance, and design leadership perspectives."), why: t("Refuerza la traducción de decisiones de diseño a evidencia profesional.", "Reforça a tradução de decisões de design em evidência profissional.", "Reinforces translating design decisions into professional evidence.") },
  { id: "ux-salon", title: "UX Salon", publisher: "UX Salon", url: "https://www.youtube.com/@UXSalon/videos", format: "channel", level: "advanced", topics: ["ux", "research", "writing", "video"], language: "en", access: "public-link", note: t("Charlas y paneles de líderes sobre UX, UX writing, investigación y futuro del campo.", "Palestras e painéis de líderes sobre UX, UX writing, pesquisa e futuro do campo.", "Talks and panels from leaders on UX, UX writing, research, and the field's future."), why: t("Aporta lenguaje y perspectivas para discutir decisiones en equipo.", "Traz linguagem e perspectivas para discutir decisões em equipe.", "Adds language and perspectives for discussing decisions with teams.") },
  { id: "caler-edwards", title: "Caler Edwards", publisher: "Caler Edwards", url: "https://www.youtube.com/@CalerEdwards/videos", format: "channel", level: "intermediate", topics: ["ui", "visual-design", "video"], language: "en", access: "public-link", note: t("Tutoriales y análisis visual para ampliar criterio de interfaz y dirección de arte digital.", "Tutoriais e análises visuais para ampliar critério de interface e direção de arte digital.", "Tutorials and visual analyses to broaden interface judgment and digital art direction."), why: t("Se utiliza como referencia estética, no como prueba de usabilidad.", "É usado como referência estética, não como prova de usabilidade.", "Use it as an aesthetic reference, not evidence of usability.") }
];
export const growthStatement = t(
  "Los materiales de estas rutas son originales de UX Academy. Los vídeos, cursos, canales, playlists y documentos enlazados pertenecen a sus editores originales y se ofrecen como referencias de acceso público; no se copian, descargan ni re-publican.",
  "Os materiais destas trilhas são originais da UX Academy. Os vídeos, cursos, canais, playlists e documentos vinculados pertencem aos seus editores originais e são oferecidos como referências de acesso público; não são copiados, baixados nem republicados.",
  "Materials in these pathways are original to UX Academy. Linked videos, courses, channels, playlists, and documents belong to their original publishers and are offered as public-access references; they are not copied, downloaded, or republished.",
);
