import { trpc } from "@/lib/trpc";
import { ExternalLink, FileUp, Link2, Plus, ShieldCheck } from "lucide-react";
import { useRef, useState } from "react";

export default function EvidenceManager({ projectId, locale }: { projectId: string; locale: "es" | "pt" | "en" }) {
  const [label, setLabel] = useState(""); const [url, setUrl] = useState(""); const fileInput = useRef<HTMLInputElement>(null); const evidence = trpc.projects.evidence.get.useQuery({ projectId }); const addLink = trpc.projects.evidence.addLink.useMutation({ onSuccess: () => { evidence.refetch(); setLabel(""); setUrl(""); } }); const addFile = trpc.projects.evidence.addFile.useMutation({ onSuccess: () => { evidence.refetch(); if (fileInput.current) fileInput.current.value = ""; } });
  const labelText = (es: string, pt: string, en: string) => locale === "es" ? es : locale === "pt" ? pt : en;
  const readFile = (file: File) => { const reader = new FileReader(); reader.onload = () => { const base64 = String(reader.result).split(",")[1]; if (base64) addFile.mutate({ projectId, label: file.name, fileName: file.name, mimeType: file.type as "application/pdf" | "image/png" | "image/jpeg" | "image/webp" | "text/plain", dataBase64: base64 }); }; reader.readAsDataURL(file); };
  if (!evidence.data?.submission) return <div className="mt-5 rounded-xl border border-dashed border-[#d7cfc4] bg-[#f8f3ec] p-4 text-xs leading-5 text-[#687168]">{labelText("Guarda primero el borrador para añadir enlaces o adjuntos privados.", "Salve primeiro o rascunho para adicionar links ou anexos privados.", "Save the draft first to add private links or attachments.")}</div>;
  return <section className="mt-6 border-t border-[#e7e0d6] pt-5"><div className="flex items-center gap-2"><ShieldCheck size={17} className="text-[#2f6048]"/><h3 className="font-serif text-xl">{labelText("Evidencias", "Evidências", "Evidence")}</h3></div><p className="mt-2 text-xs leading-5 text-[#687168]">{labelText("Solo añade trabajo propio o autorizado. Los archivos permitidos son PDF, PNG, JPG, WEBP o TXT hasta 7 MB; los enlaces deben usar HTTPS.", "Adicione apenas trabalho próprio ou autorizado. Arquivos permitidos: PDF, PNG, JPG, WEBP ou TXT até 7 MB; links precisam usar HTTPS.", "Add only your own or authorized work. Allowed files are PDF, PNG, JPG, WEBP, or TXT up to 7 MB; links must use HTTPS.")}</p><div className="mt-4 grid gap-3 sm:grid-cols-[1fr_1.3fr_auto]"><input value={label} onChange={event => setLabel(event.target.value)} className="rounded-xl border border-[#d8d0c5] bg-white px-3 py-2 text-sm" placeholder={labelText("Etiqueta", "Rótulo", "Label")}/><input value={url} onChange={event => setUrl(event.target.value)} className="rounded-xl border border-[#d8d0c5] bg-white px-3 py-2 text-sm" placeholder="https://"/><button type="button" disabled={!label.trim() || !url.trim() || addLink.isPending} onClick={() => addLink.mutate({ projectId, label, url })} className="inline-flex items-center justify-center gap-1 rounded-xl bg-[#e9e3d9] px-3 py-2 text-sm font-bold text-[#334038] disabled:opacity-40"><Link2 size={15}/>{labelText("Enlazar", "Vincular", "Link")}</button></div><div className="mt-3"><input ref={fileInput} onChange={event => { const file = event.target.files?.[0]; if (file) readFile(file); }} accept="application/pdf,image/png,image/jpeg,image/webp,text/plain" type="file" className="sr-only" id={`file-${projectId}`}/><label htmlFor={`file-${projectId}`} className="inline-flex cursor-pointer items-center gap-2 rounded-xl border border-[#cfc5b7] px-3 py-2 text-sm font-bold text-[#3d4a40]"><FileUp size={16}/>{addFile.isPending ? labelText("Subiendo…", "Enviando…", "Uploading…") : labelText("Adjuntar archivo", "Anexar arquivo", "Attach file")}</label></div>{evidence.data.evidence.length > 0 && <div className="mt-4 space-y-2">{evidence.data.evidence.map(item => <div key={item.id} className="flex items-center justify-between gap-3 rounded-xl bg-[#f3eee6] px-3 py-2.5 text-sm"><span className="min-w-0 truncate text-[#455247]">{item.label}</span><a href={item.externalUrl || item.storageUrl || "#"} target="_blank" rel="noreferrer" className="shrink-0 text-[#2f6048]" aria-label={labelText("Abrir evidencia", "Abrir evidência", "Open evidence")}><ExternalLink size={15}/></a></div>)}</div>}</section>;
}
